In [26]:
from pathlib import Path

import pandas as pd
from tqdm import tqdm

In [4]:
faces_dir = Path('../data/faces')
subdirs = [x for x in faces_dir.iterdir()]

In [27]:
for subdir in tqdm(subdirs):
    files = [x for x in subdir.iterdir()]
    for file in tqdm(files, leave=False):
        df = pd.read_csv(str(file), index_col=0)
        df = df.assign(pct_of_frame=df.apply(lambda row: (row['x2'] - row['x1']) * (row['y2'] - row['y1']), axis=1))
        df.to_csv(file)

100%|██████████| 83/83 [04:37<00:00,  3.34s/it]

In [8]:
files = [x for x in subdirs[1].iterdir()]
df = pd.read_csv(str(files[0]), index_col=0)
df.head()

,x1,y1,x2,y2,right_eye_x,right_eye_y,left_eye_x,left_eye_y,nose_x,nose_y,...,img_height,filepath,encoding,series_id,episode_id,season,episode,filename,distance_from_center,pct_of_frame
0,0.726,0.236,0.775,0.319,0.735,0.275,0.741,0.274,0.736,0.295,...,1080,/home/amos/media/tv/Cheers.S01-S11.1080p.BluRa...,-0.0955279\n0.0279929\n0.116944\n-0.0220034\n-...,83399,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,433.22,0.40
1,0.628,0.333,0.666,0.390,0.646,0.352,0.660,0.358,0.653,0.369,...,1080,/home/amos/media/tv/Cheers.S01-S11.1080p.BluRa...,-0.015734\n0.0687631\n0.0292901\n-0.0263472\n-...,83399,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,258.88,0.21
2,0.177,0.194,0.199,0.231,0.182,0.212,0.191,0.209,0.186,0.217,...,1080,/home/amos/media/tv/Cheers.S01-S11.1080p.BluRa...,-0.0872673\n0.0704359\n0.0859115\n-0.0428546\n...,83399,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,547.01,0.08
3,0.596,0.258,0.617,0.294,0.605,0.271,0.613,0.272,0.610,0.279,...,1080,/home/amos/media/tv/Cheers.S01-S11.1080p.BluRa...,-0.0823594\n0.0407621\n0.0450835\n-0.024345\n-...,83399,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,286.31,0.07
4,0.628,0.334,0.666,0.391,0.647,0.354,0.660,0.359,0.653,0.370,...,1080,/home/amos/media/tv/Cheers.S01-S11.1080p.BluRa...,0.00116389\n0.0957981\n0.0143032\n-0.021525\n-...,83399,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,258.31,0.21

In [25]:
df['pct_of_frame'] = df.apply(lambda row: (row['x2'] - row['x1']) * (row['y2'] - row['y1']), axis=1)

df['face_width'] = df.apply(lambda x: (x['x2'] * x['img_width']) - (x['x1'] * x['img_width']), axis=1)
df['face_height'] = df.apply(lambda x: (x['y2'] * x['img_height']) - (x['y1'] * x['img_height']), axis=1)
df['face_area'] = df['face_width'] * df['face_height']
df['face_pct_of_frame'] = df.apply(lambda x: x['face_area']/ (x['img_width'] * x['img_height']), axis=1)
df.head()

,x1,y1,x2,y2,right_eye_x,right_eye_y,left_eye_x,left_eye_y,nose_x,nose_y,...,episode_id,season,episode,filename,distance_from_center,pct_of_frame,face_width,face_height,face_area,face_pct_of_frame
0,0.726,0.236,0.775,0.319,0.735,0.275,0.741,0.274,0.736,0.295,...,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,433.22,0.004067,70.56,89.64,6324.9984,0.004067
1,0.628,0.333,0.666,0.390,0.646,0.352,0.660,0.358,0.653,0.369,...,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,258.88,0.002166,54.72,61.56,3368.5632,0.002166
2,0.177,0.194,0.199,0.231,0.182,0.212,0.191,0.209,0.186,0.217,...,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,547.01,0.000814,31.68,39.96,1265.9328,0.000814
3,0.596,0.258,0.617,0.294,0.605,0.271,0.613,0.272,0.610,0.279,...,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,286.31,0.000756,30.24,38.88,1175.7312,0.000756
4,0.628,0.334,0.666,0.391,0.647,0.354,0.660,0.359,0.653,0.370,...,NaN,7,10,Cheers.S07E10.1080p.BluRay.x265-RARBG.mp4,258.31,0.002166,54.72,61.56,3368.5632,0.002166

In [14]:
(.775 - .726) * (.319-.236)

0.004067000000000005

In [ ]:
()