In [1]:
import os
import sys

import numpy as np
import pandas as pd
import plotly.express as px
import dataframe_image as dfi
import plotly.graph_objects as go
from scipy import stats 
import sqlalchemy as db

sys.path.append(os.path.abspath(os.path.join('../..')))

from utils import *

In [2]:
username = "amos"
password = "M0$hicat"
host = "192.168.0.131"
port = "3306"
database = "CineFaceDW"
connection_string = f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}'
engine = db.create_engine(connection_string)

In [3]:
name = "Christopher Nolan"

In [4]:
df = pd.read_sql(f"SELECT * FROM vwWorksByDirector WHERE kind = 'movie'", engine)
df

,person_id,person_name,title,year,kind,runtime,fact_id,imdb_id,work_id,avg_size,...,z_v_density_tv,z_v_density_tv_g,z_pct_face_tv,z_pct_face_tv_g,z_v_pct_face_tv,z_v_pct_face_tv_g,z_pct_top1_tv,z_pct_top1_tv_g,z_v_pct_top1_tv,z_v_pct_top1_tv_g
0,100036,D.W. Griffith,The Avenging Conscience: or 'Thou Shalt Not Kill',1914,movie,78.0,251,3643,32807,0.0176,...,None,None,None,None,None,None,None,None,None,None
1,41611,Giovanni Pastrone,Cabiria,1914,movie,148.0,256,3740,32809,0.0056,...,None,None,None,None,None,None,None,None,None,None
2,1037794,Lois Weber,Hypocrites,1915,movie,54.0,270,4134,32812,0.0089,...,None,None,None,None,None,None,None,None,None,None
3,100036,D.W. Griffith,Judith of Bethulia,1914,movie,61.0,272,4181,32813,0.0087,...,None,None,None,None,None,None,None,None,None,None
4,1307858,Colin Campbell,The Spoilers,1914,movie,110.0,289,4630,32816,0.0101,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7633,309,Pedro Almodóvar,Dolor y gloria,2019,movie,113.0,9772,8291806,56846,0.0374,...,None,None,None,None,None,None,None,None,None,None
7634,67367,Rian Johnson,Knives Out,2019,movie,130.0,9778,8946378,56847,0.0529,...,None,None,None,None,None,None,None,None,None,None
7635,67367,Rian Johnson,Glass Onion,2022,movie,139.0,9447,11564570,56848,0.0332,...,None,None,None,None,None,None,None,None,None,None
7636,67367,Rian Johnson,Wake Up Dead Man,2025,movie,144.0,9464,14364480,56849,0.0515,...,None,None,None,None,None,None,None,None,None,None
7637,14392,Kathryn Bigelow,A House of Dynamite,2025,movie,112.0,9495,32376165,56850,0.0430,...,None,None,None,None,None,None,None,None,None,None

In [5]:
g = pd.read_sql("SELECT * FROM vwDirectorStats WHERE cnt > 5", engine)
g

,person_id,name,cnt,avg_f_per_fr,z_size_mv_mean,z_size_mv_g_mean,z_size_mv_std,z_size_mv_g_std,z_top1_mv_mean,z_top1_mv_g_mean,...,z_v_density_mv_mean,z_v_density_mv_g_mean,z_pct_top1_mv_mean,z_pct_top1_mv_g_mean,z_v_pct_top1_mv_mean,z_v_pct_top1_mv_g_mean,z_pct_face_mv_mean,z_pct_face_mv_g_mean,z_v_pct_face_mv_mean,z_v_pct_face_mv_g_mean
0,1,George Lucas,6,1.597648,-0.053352,0.814914,0.783111,0.766601,-0.190065,0.802465,...,0.000000,0.000000,0.277344,0.991328,-0.111087,-0.397079,-0.226912,0.660440,-0.229422,0.845807
1,40,Orson Welles,9,1.770517,0.697528,0.110828,0.808529,0.445027,0.889053,0.204514,...,0.745900,0.449870,0.888112,0.327788,0.070874,0.214835,0.630211,0.140793,1.023617,0.451762
2,68,Fritz Lang,33,1.873031,-0.432220,-0.640721,0.738070,0.369027,-0.447708,-0.691414,...,0.064489,-0.170618,0.384600,-0.147534,0.320935,0.367024,-0.660249,-0.775029,-0.107610,-0.558840
3,138,Quentin Tarantino,7,1.581424,-0.217380,0.863364,0.969357,1.334367,-0.287119,0.842447,...,-0.286160,0.325392,0.116981,1.032773,-0.151320,-0.850129,-0.378893,0.631704,0.342752,1.289849
4,190,Clint Eastwood,32,2.017244,-0.416212,0.314150,0.702603,0.667530,-0.269060,0.586161,...,0.029670,0.063425,-0.578839,0.328151,0.495116,0.198262,-0.136572,0.651149,-0.389156,0.490620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,940663,Chester M. Franklin,8,1.618405,0.397221,-0.568999,0.979921,0.185540,0.344414,-0.740273,...,-0.017444,0.621329,-0.074203,0.162069,0.396381,0.419476,0.359364,-0.866964,-0.004262,-0.903669
329,1021685,E. Mason Hopper,6,1.722700,-0.272303,-0.544496,0.875573,0.382297,-0.368806,-0.691033,...,-0.234674,-0.300615,-0.142999,-0.409118,0.188546,0.391993,-0.542793,-0.771631,-0.404528,-0.799606
330,1036754,Reginald Barker,7,1.812715,0.462617,-0.635704,0.387553,0.375400,0.511501,-0.746425,...,0.359743,0.539909,-0.135964,-0.138941,0.476722,0.568228,0.635482,-0.770480,0.400587,-0.831591
331,1065336,Melville W. Brown,6,1.830765,-0.722426,-0.799145,0.455469,0.263664,-0.791800,-0.919072,...,-0.030822,-0.239791,-0.170180,-0.596750,0.235600,0.280355,-0.923024,-0.982991,-0.877001,-1.104247
332,1225777,Leigh Jason,7,2.091450,0.035561,-0.406215,0.444228,0.174203,0.024545,-0.447347,...,0.075440,-0.314887,-0.587623,-0.964119,-0.176007,0.104267,0.400758,-0.178973,0.090061,-0.432101

In [6]:
nolan = df[df['person_name'] == name]

# Nolan vs. Other Directors

## Scale

### Avg. Size vs. Std. Size

In [7]:
x = "z_size_mv_g_mean"
y = "z_v_size_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name], 
                              x_title="Avg. Size (Z Score)", 
                              y_title="Size Variance (Z Score)", 
                              title="Christopher Nolan: Avg. Face Size vs. Std. Face Size", 
                              width=1200,
                              height=600,
                              dst="./plots/nolan/nolan_size_v_variance.png")

Size and variance are closely related (correlation of 0.93). Most directors are near the regression line, but Nolan sits further below than any other director. What this suggests is that while Nolan prefers closer shots, the variance in face size within a film is low, meaning he likes large but consistent face scales.

In [8]:
print("Avg. Size Percentile:", stats.percentileofscore(g['z_size_mv_g_mean'], g[g['name'] == name].iloc[0]['z_size_mv_g_mean']))
print("Std. Size Percentile:", stats.percentileofscore(g['z_v_size_mv_g_mean'], g[g['name'] == name].iloc[0]['z_v_size_mv_g_mean']))

Avg. Size Percentile: 98.4984984984985
Std. Size Percentile: 94.29429429429429

### Avg. Top 1 Size vs. Std. Top 1 Size

In [9]:
x = "z_top1_mv_g_mean"
y = "z_v_top1_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name], 
                              x_title="Avg. Top 1 Size (Z Score)", 
                              y_title="Top 1 Size Std. (Z Score)", 
                              title="Christopher Nolan: Avg. Top 1 Size vs. Std. Top 1 Size", 
                              width=1200,
                              height=600,
                              dst="./plots/nolan/nolan_top_mean_v_top_std.png")

If we only look at the largest face within a frame, Nolan is closer to the pack, though he still sits lower from the regression line than anyone else. That Nolan is more similar to other directors when only looking at the largest face means that his overall average is higher because he prefers single shots rather than two-shots or establishing shots.

In [10]:
print("Top 1 Avg. Size:", stats.percentileofscore(g['z_top1_mv_g_mean'], g[g['name'] == name].iloc[0]['z_top1_mv_g_mean']))
print("Top 1 Std. Size:", stats.percentileofscore(g['z_v_top1_mv_g_mean'], g[g['name'] == name].iloc[0]['z_v_top1_mv_g_mean']))

Top 1 Avg. Size: 97.8978978978979
Top 1 Std. Size: 90.990990990991

### Avg. Face Size vs. Std. of Face Size Std.

This plot maps a director's average shot scale (X) against their cross-project variance (Y). While the x-axis shows the career-wide average face size, the y-axis measures how much those averages shift from one movie to the next. A high y-score indicates a director whose 'typical' shot size is highly *inconsistent* across their filmography. A low y-score indicates a director who is highly *consistent* across their filmography.

In [11]:
x = "z_size_mv_g_mean"
y = "z_size_mv_g_std"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name], 
                              x_title="Avg. Face Size (Z Score)", 
                              y_title="Std. of std. Face Size", 
                              title="Christopher Nolan: Avg. Face Size vs. Std. of Avg. Face Size", 
                              width=1200,
                              height=600,
                              dst="./plots/nolan/nolan_size_mean_v_size_std_std.png")

In [12]:
print("Top 1 Avg. Size:", stats.percentileofscore(g['z_size_mv_g_mean'], g[g['name'] == name].iloc[0]['z_size_mv_g_mean']))
print("Top 1 Std. of Avg. Size:", stats.percentileofscore(g['z_size_mv_g_std'], g[g['name'] == name].iloc[0]['z_size_mv_g_std']))

Top 1 Avg. Size: 98.4984984984985
Top 1 Std. of Avg. Size: 99.0990990990991

Nolan is relatively high on the std. of std. What does this mean? It means Nolan has changed his face scale considerably between films.

### Avg. Size Variance vs. Std. of Size Variance

This plot looks at how face sizes vary within a movie vs. how the variance varies between movies. The x axis measures the *internal* variance while the y axis measures the *external* variance. A high value on the x axis means the director has a lot of variation in shot scales *within* a film. A high value on the y axis means the director is "consistenly inconsistent." A representative example is Sergio Leone who likes to vary his shot scales within his films (think of the sparse landscapes contrasted with extreme closeups in a film like *The Good, the Bad, and the Ugly* [1966]). But he also varies shot scales *between* movies, meaning on some films he has a lot of variation in scales while on some films he maintains a more consistent scale.

In [13]:
x = "z_v_size_mv_g_mean"
y = "z_v_size_mv_g_std"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name], 
                              x_title="Std. Face Size (Z Score)", 
                              y_title="Std. of std. Face Size Variance (Z Score)", 
                              title="Christopher Nolan: Std. Face Size vs. Std. of Face Size Variance", 
                              width=1200,
                              height=600,
                              dst="./plots/nolan/nolan_size_mean_v_size_std.png")

In [14]:
print("Std. Size:", stats.percentileofscore(g['z_v_size_mv_g_mean'], g[g['name'] == name].iloc[0]['z_v_size_mv_g_mean']))
print("Std. of Std. Size:", stats.percentileofscore(g['z_v_size_mv_g_std'], g[g['name'] == name].iloc[0]['z_v_size_mv_g_std']))

Std. Size: 94.29429429429429
Std. of Std. Size: 94.29429429429429

Nolan sits right on the regression line, suggesting a more "normal" pattern even though he is relatively high on both metrics. Nolan likes to vary his scales *between* films but in a way that is expected give his variation *within* his films.

### Avg. Size vs. Avg. Dispersion

In [15]:
x = "z_size_mv_g_mean"
y = "z_disp_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name], 
                              x_title="Avg. Size (Z Score)", 
                              y_title="Avg. Dispersion (Z Score)", 
                              title="Christopher Nolan: Avg. Face Size vs. Avg. Dispersion", 
                              width=1200,
                              height=600,
                              dst="./plots/nolan/nolan_size_vs_disp.png")

In [16]:
print("Avg. Size:", stats.percentileofscore(g['z_size_mv_g_mean'], g[g['name'] == name].iloc[0]['z_size_mv_g_mean']))
print("Avg. Dispersion:", stats.percentileofscore(g['z_disp_mv_mean'], g[g['name'] == name].iloc[0]['z_disp_mv_mean']))

Avg. Size: 98.4984984984985
Avg. Dispersion: 4.504504504504505

### Avg. Size vs. Percent Singles

In [17]:
x = "z_size_mv_g_mean"
y = "z_pct_top1_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name], 
                              x_title="Avg. Size (Z Score)", 
                              y_title="Percent Singles (Z Score)", 
                              title="Christopher Nolan: Avg. Face Size vs. Percent Singles", 
                              width=1200,
                              height=600,
                              dst="./plots/nolan/nolan_size_vs_singles.png")

In [18]:
print("Avg. Size:", stats.percentileofscore(g['z_size_mv_g_mean'], g[g['name'] == name].iloc[0]['z_size_mv_g_mean']))
print("Percent Singles:", stats.percentileofscore(g['z_pct_top1_mv_g_mean'].dropna(), g[g['name'] == name].iloc[0]['z_pct_top1_mv_g_mean']))

Avg. Size: 98.4984984984985
Percent Singles: 100.0

## Density

### Avg. Faces per Frame vs. Avg. Size

In [19]:
x = "z_f_per_fr_mv_g_mean"
y = "z_size_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Avg. Faces per Frame vs. Avg. Face Size",
                              x_title="Avg. Faces per Frame (Z Score)",
                              y_title="Avg. Face Size (Z Score)",
                              dst="./plots/nolan/nolan_faces_per_fr_vs_avg_size.png",
                              width=1200,
                              height=600)

In [20]:
print("Faces per Frame Percentile:", stats.percentileofscore(g['z_f_per_fr_mv_g_mean'], g[g['name'] == name].iloc[0]['z_f_per_fr_mv_g_mean']))
print("Avg. Size Percentile:", stats.percentileofscore(g['z_size_mv_g_mean'], g[g['name'] == name].iloc[0]['z_size_mv_g_mean']))

Faces per Frame Percentile: 3.3033033033033035
Avg. Size Percentile: 98.4984984984985

In [21]:
x = "z_f_per_fr_mv_g_mean"
y = "z_pct_top1_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title=f"{name}: Avg. Faces per Frame vs. Pct. Singles",
                              x_title="Avg. Faces per Frame (Z Score)",
                              y_title="% Singles (Z Score)",
                              dst="./plots/nolan/nolan_faces_per_fr_vs_singles.png",
                              width=1200,
                              height=600)

In [22]:
print("Faces per Frame Percentile:", stats.percentileofscore(g['z_f_per_fr_mv_g_mean'], g[g['name'] == name].iloc[0]['z_f_per_fr_mv_g_mean']))
print("Pct. Singles Percentile:", stats.percentileofscore(g['z_pct_top1_mv_g_mean'], g[g['name'] == name].iloc[0]['z_pct_top1_mv_g_mean']))

Faces per Frame Percentile: 3.3033033033033035
Pct. Singles Percentile: 100.0

### Faces per Frame vs. Dispersion

In [23]:
x = "z_f_per_fr_mv_g_mean"
y = "z_disp_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Faces per Frame vs. Dispersion",
                              width=1200,
                              height=600,
                              x_title="Faces per Frame (Z Score)",
                              y_title="Dispersion (Z Score)",
                              dst="./plots/nolan/nolan_f_per_fr_vs_disp.png"
                              )

In [24]:
print("Pct. Singles Percentile:", stats.percentileofscore(g['z_f_per_fr_mv_g_mean'], g[g['name'] == name].iloc[0]['z_f_per_fr_mv_g_mean']))
print("Dispersion Percentile:", stats.percentileofscore(g['z_disp_mv_g_mean'], g[g['name'] == name].iloc[0]['z_disp_mv_g_mean']))

Pct. Singles Percentile: 3.3033033033033035
Dispersion Percentile: 3.3033033033033035

### Avg. Density vs. Avg. Size

In [25]:
x = "z_density_mv_g_mean"
y = "z_v_dist_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Avg. Density vs. Avg. Size",
                              width=1200,
                              height=600,
                              x_title="Avg. Density (Z Score)",
                              y_title="Avg. Size (Z Score)",
                              dst="./plots/nolan/nolan_density.png"
                              )

In [26]:
print("Density Percentile:", stats.percentileofscore(g['z_density_mv_g_mean'], g[g['name'] == name].iloc[0]['z_density_mv_g_mean']))

Density Percentile: 27.62762762762763

### Avg. Density vs. Faces per Frame

In [27]:
x = "z_density_mv_g_mean"
y = "z_f_per_fr_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Avg. Density vs. Avg. Faces per Frame",
                              width=1200,
                              height=600,
                              x_title="Avg. Density (Z Score)",
                              y_title="Avg. Faces per Frame (Z Score)",
                              dst="./plots/nolan/nolan_density_f_per_fr.png"
                              )

In [28]:
print("Density Percentile:", stats.percentileofscore(g['z_density_mv_g_mean'].dropna(), g[g['name'] == name].iloc[0]['z_density_mv_g_mean']))

Density Percentile: 27.62762762762763

## Composition

### Avg. Distance vs. Std. Distance

In [29]:
x = "z_dist_mv_g_mean"
y = "z_v_dist_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Avg. Distance from Center vs. Std. Distance from Center",
                              x_title="Avg. Distance from Center (Z Score)",
                              y_title="Std. Distance from Center (Z Score)",
                              dst="./plots/nolan/nolan_avg_dist_vs_std_dist.png",
                              width=1200,
                              height=600)

### Avg. Distance vs. Gini Score

In [30]:
x = "z_dist_mv_g_mean"
y = "z_gini_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Avg. Distance from Center vs. Gini Score",
                              x_title="Avg. Distance from Center (Z Score)",
                              y_title="Gini Score (Z Score)",
                              dst="./plots/nolan/nolan_avg_dist_vs_gini.png",
                              width=1200,
                              height=600)

In [31]:
print("Gini Percentile:", stats.percentileofscore(g['z_gini_mv_g_mean'], g[g['name'] == name].iloc[0]['z_gini_mv_g_mean']))
print("Avg. Distance:", stats.percentileofscore(g['z_dist_mv_g_mean'], g[g['name'] == name].iloc[0]['z_dist_mv_g_mean']))

Gini Percentile: 100.0
Avg. Distance: 0.3003003003003003

### Avg. Distance vs. Avg. Dispersion

In [32]:
x = "z_dist_mv_g_mean"
y = "z_disp_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Avg. Distance from Center vs. Dispersion",
                              x_title="Avg. Distance from Center (Z Score)",
                              y_title="Avg. Dispersion (Z Score)",
                              dst="./plots/nolan/nolan_avg_dist_vs_disp.png",
                              width=1200,
                              height=600)

In [33]:
print("Distance Percentile:", stats.percentileofscore(g['z_dist_mv_g_mean'], g[g['name'] == name].iloc[0]['z_dist_mv_g_mean']))
print("Dispersion Percentile:", stats.percentileofscore(g['z_disp_mv_g_mean'], g[g['name'] == name].iloc[0]['z_disp_mv_g_mean']))

Distance Percentile: 0.3003003003003003
Dispersion Percentile: 3.3033033033033035

### Std. Distance vs. Gini

In [34]:
x = "z_v_dist_mv_g_mean"
y = "z_gini_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Variance of Distance to Center vs. Gini Score",
                              x_title="Variance Distance (Z Score)",
                              y_title="Gini (Z Score)",
                              width=1200,
                              height=600,
                              dst="./plots/nolan/nolan_std_distance_vs_gini.png")

In [35]:
print("Std. Distance Percentile:", stats.percentileofscore(g['z_v_dist_mv_g_mean'], g[g['name'] == name].iloc[0]['z_v_dist_mv_g_mean']))
print("Gini Percentile:", stats.percentileofscore(g['z_gini_mv_g_mean'], g[g['name'] == name].iloc[0]['z_gini_mv_g_mean']))

Std. Distance Percentile: 80.18018018018019
Gini Percentile: 100.0

### Vertical Discipline vs. Horizontal Spread

In [36]:
x = "z_vert_mv_g_mean"
y = "z_h_spread_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Vertical Discipline vs. Horizontal Spread",
                              x_title="Vertical Discipline (Z Score)",
                              y_title="Horizontal Spread (Z Score)",
                              dst="./plots/nolan/nolan_vert_vs_spread.png",
                              width=1200,
                              height=600)

In [37]:
print("Vertical Discipline Percentile:", stats.percentileofscore(g['z_vert_mv_g_mean'], g[g['name'] == name].iloc[0]['z_vert_mv_g_mean']))
print("Horizontal Spread Percentile:", stats.percentileofscore(g['z_h_spread_mv_g_mean'], g[g['name'] == name].iloc[0]['z_h_spread_mv_g_mean']))

Vertical Discipline Percentile: 72.37237237237237
Horizontal Spread Percentile: 47.447447447447445

### Dispersion vs. Gini

In [38]:
x = "z_disp_mv_g_mean"
y = "z_gini_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title="Dispersion vs. Gini",
                              x_title="Dispersion (Z Score)",
                              y_title="Gini (Z Score)",
                              dst="./plots/nolan/nolan_disp_vs_gini.png",
                              width=1200,
                              height=600)

In [39]:
print("Avg. Dispersion Percentile:", stats.percentileofscore(g['z_disp_mv_g_mean'], g[g['name'] == name].iloc[0]['z_disp_mv_g_mean']))
print("Gini Percentile:", stats.percentileofscore(g['z_gini_mv_g_mean'], g[g['name'] == name].iloc[0]['z_gini_mv_g_mean']))

Avg. Dispersion Percentile: 3.3033033033033035
Gini Percentile: 100.0

# Nolan's Films vs. Sample

## Avg. Faces per Frame vs. Avg. Size

In [40]:
x = "avg_f_per_fr"
y = "z_size_mv_g"
plot_directors_titles_sample(df, 
                             x, 
                             y, 
                             name, 
                             title="Faces per Frame vs. Face Size", 
                             x_title="Faces per Frame", 
                             y_title="Size (Z Score)", 
                             layout=layout, 
                             trendline='lowess',
                             width=1200,
                             height=600,
                             trendline_options=dict(frac=0.5),
                             titles=nolan['title'].tolist(), 
                             dst="./plots/nolan/nolan_films_f_per_fr_v_size.png")

In [41]:
x = "z_size_mv_g"
y = "z_gini_mv_g"
plot_directors_titles_sample(df, 
                             x, 
                             y, 
                             name, 
                             title="Avg. Size vs. Gini Score", 
                             x_title="Avg. Size", 
                             y_title="Gini", 
                             layout=layout, 
                             titles=nolan['title'].tolist(), 
                             dst="./plots/nolan/nolan_films_size_v_gini.png")

## Dispersion vs. Gini

In [42]:
x = "z_disp_mv_g"
y = "z_gini_mv_g"
plot_directors_titles_sample(df, 
                             x, 
                             y, 
                             name, 
                             title="Dispersion vs. Gini Score", 
                             x_title="Dispersion", 
                             y_title="Gini", 
                             layout=layout, 
                             trendline='ols',
                             titles=nolan['title'].tolist(), 
                             dst="./plots/nolan/nolan_films_disp_v_gini.png")

# Career Stats

In [43]:
nolan = df[df['person_name'] == name]

## Percentiles

In [44]:
names = {
    "z_size_mv_g": "Avg. Size",
    "z_f_per_fr_mv_g": "Avg. Faces per Frame",
    "z_gini_mv_g": "Avg. Gini",
    "z_pct_top1_mv_g": "Pct. Singles",
    "z_dist_mv_g": "Avg. Distance",
    "z_vert_mv_g": "Vertical Discipline",
    "z_h_spread_mv_g": "Horizontal Spread"
}

y = ["z_size_mv_g", "z_f_per_fr_mv_g", "z_gini_mv_g", "z_pct_top1_mv_g", "z_dist_mv_g", "z_vert_mv_g", "z_h_spread_mv_g"]
sample_ranks = df[y].rank(pct=True) * 100

results = df[['title', 'year', 'person_name']].copy()
results[y] = sample_ranks

# 4. Now filter for Nolan
nolan_global_pct = results[results['person_name'] == "Christopher Nolan"].drop_duplicates(subset=['title'])

# 5. Final Formatting: Sort and Rename
nolan_global_pct = nolan_global_pct.sort_values(by='year', ascending=True)
nolan_global_pct = nolan_global_pct.drop('person_name', axis=1).round(1)
nolan_global_pct = nolan_global_pct.rename(names, axis=1)
styled_table = (
    nolan_global_pct
    .style
    .hide(axis="index")
    .format(precision=1)  # This is the key line for the image export
)

await dfi.export_async(styled_table, "./data/nolan/nolan_percentile_matrix.png")
nolan_global_pct

,title,year,Avg. Size,Avg. Faces per Frame,Avg. Gini,Pct. Singles,Avg. Distance,Vertical Discipline,Horizontal Spread
5268,Following,1998,94.7,0.4,99.9,99.5,0.3,99.0,14.8
7318,Memento,2000,99.9,0.4,99.7,99.6,0.2,82.6,32.6
7319,Insomnia,2002,99.7,1.4,96.0,99.1,1.8,38.6,96.9
7247,Batman Begins,2005,98.4,13.9,81.5,97.1,10.5,21.8,78.7
7326,The Prestige,2006,97.7,2.4,89.0,99.0,11.7,22.1,39.1
7249,The Dark Knight,2008,85.9,67.6,30.5,87.0,51.8,19.6,77.7
7379,Inception,2010,97.3,9.7,86.9,93.3,10.1,24.5,53.2
7378,The Dark Knight Rises,2012,53.5,59.1,59.2,83.0,28.1,69.6,48.3
7251,Interstellar,2014,90.9,1.3,99.8,98.6,0.1,95.2,17.1
7337,Dunkirk,2017,63.2,74.1,61.1,79.2,23.8,54.2,25.7
7258,Tenet,2020,76.4,2.9,99.1,97.6,1.0,95.9,27.6
6045,Oppenheimer,2023,62.9,47.8,98.0,80.8,3.1,94.6,31.6

## Correlation Matrix

In [45]:
y = ["z_size_mv_g", "z_f_per_fr_mv_g", "z_gini_mv_g", "z_pct_top1_mv_g", "z_dist_mv_g", "z_vert_mv_g", "z_h_spread_mv_g"]

In [46]:
names = {
    "z_size_mv_g": "Avg. Size",
    "z_f_per_fr_mv_g": "Avg. Faces per Frame",
    "z_gini_mv_g": "Avg. Gini",
    "z_pct_top1_mv_g": "Pct. Singles",
    "z_dist_mv_g": "Avg. Distance",
    "z_vert_mv_g": "Vertical Discipline",
    "z_h_spread_mv_g": "Horizontal Spread"
}

### Nolan

In [47]:
corr_matrix = nolan[y].copy()
corr_matrix = corr_matrix.corr().round(2)
corr_matrix = corr_matrix.rename(index=names, columns=names)
fig = px.imshow(
    corr_matrix,
    text_auto=".2f",               # Shows the values inside the cells
    aspect="auto",                 # Squares the cells
    color_continuous_scale='RdBu_r', # Red-Blue scale (Red = Pos, Blue = Neg)
    zmin=-1, zmax=1,               # Standard correlation bounds
    title="Christopher Nolan: Metric Correlation Matrix",
    labels=dict(color="Correlation")
)
fig.update_layout(layout)
fig.update_layout(title=dict(text="Christopher Nolan: Metric Correlation Matrix", xanchor="center"))
fig.write_image("./plots/nolan/nolan_corr_matrix.png", width=1200, height=600, scale=2)
fig.show()

### Sample

In [48]:
corr_matrix = df[y].copy()
corr_matrix = corr_matrix.corr().round(2)
corr_matrix = corr_matrix.rename(index=names, columns=names)
fig = px.imshow(
    corr_matrix,
    text_auto=".2f",               # Shows the values inside the cells
    aspect="auto",                 # Squares the cells
    color_continuous_scale='RdBu_r', # Red-Blue scale (Red = Pos, Blue = Neg)
    zmin=-1, zmax=1,               # Standard correlation bounds
    labels=dict(color="Correlation")
)
fig.update_layout(layout)
fig.update_layout(title=dict(text="Sample: Metric Correlation Matrix", xanchor="center", y=0.95))
fig.write_image("./plots/nolan/nolan_sample_matrix.png", width=1200, height=600, scale=2)
fig.show()

### Difference

In [49]:
sample_corr = df[y].copy()
nolan_corr = nolan[y].copy()
sample_corr = sample_corr.corr().round(2)
nolan_corr = nolan_corr.corr().round(2)
diff = nolan_corr - sample_corr
diff = diff.rename(index=names, columns=names)
fig = px.imshow(
    diff,
    text_auto=".2f",               # Shows the values inside the cells
    aspect="auto",                 # Squares the cells
    color_continuous_scale='RdBu_r', # Red-Blue scale (Red = Pos, Blue = Neg)
    zmin=-1, zmax=1,               # Standard correlation bounds
    labels=dict(color="Correlation")
)
fig.update_layout(layout)
fig.update_layout(title=dict(text="Nolan vs. Sample: Difference in Correlation", xanchor="center", y=0.95))
fig.write_image("./plots/nolan/nolan_diff_matrix.png", width=1200, height=600, scale=2)
fig.show()

## Avg. Size by Year

In [50]:
x = "year"
y = ["z_size_mv_g", "z_top1_mv_g"]
traces_names = {"z_size_mv_g": "Avg. Face Size", 
                "z_top1_mv_g": "Top 1 Avg. Face Size"}
plot_director_films(df, 
                    x, 
                    y, 
                    name, 
                    line=True, 
                    x_name='Year',
                    y_name='Avg. Size (Z Score)',
                    title="Christopher Nolan: Avg. Face Size by Year",
                    # trace_names=traces_names,
                    marker_labels=True,
                    width=1200,
                    height=600,
                    text_size=16,
                    dst="./plots/nolan/nolan_films_avg_size_vs_year.png")

In [51]:
nolan[y].corr()

             z_size_mv_g  z_top1_mv_g
z_size_mv_g     1.000000     0.958709
z_top1_mv_g     0.958709     1.000000

## Avg. Size, Gini vs. Year

In [52]:
x = "year"
y = ["z_size_mv_g", "z_gini_mv_g"]
traces_names = {"z_size_mv_g": "Avg. Face Size", 
                "z_gini_mv_g": "Gini"}
plot_director_films(df, 
                    x, 
                    y, 
                    name, 
                    line=True, 
                    x_name='Year',
                    y_name='Z Score',
                    title="Christopher Nolan: Avg. Face Size and Gini Score by Year",
                    # trace_names=traces_names,
                    marker_labels=True,
                    width=1200,
                    height=600,
                    text_size=16,
                    dst="./plots/nolan/nolan_films_avg_size_gini_vs_year.png")

In [53]:
nolan[nolan['year'] <= 2008][y].corr()

             z_size_mv_g  z_gini_mv_g
z_size_mv_g     1.000000     0.530075
z_gini_mv_g     0.530075     1.000000

In [54]:
nolan[nolan['year'] > 2008][y].corr()

             z_size_mv_g  z_gini_mv_g
z_size_mv_g     1.000000     0.257849
z_gini_mv_g     0.257849     1.000000

## Avg. Distance by Year

In [55]:
x = "year"
y = ["z_dist_mv_g", "z_v_dist_mv_g"]
plot_director_films(df, 
                    x, 
                    y, 
                    name, 
                    line=True, 
                    x_name='Year',
                    y_name='Avg. Distance (Z Score)',
                    title="Christopher Nolan: Distance to Center by Year",
                    marker_labels=True,
                    width=1200,
                    height=600,
                    text_size=16,
                    dst="./plots/nolan_dist_vs_year.png")

In [56]:
nolan[y].corr()

               z_dist_mv_g  z_v_dist_mv_g
z_dist_mv_g       1.000000       0.861663
z_v_dist_mv_g     0.861663       1.000000

## Avg. Faces per Frame, Size vs. Year

In [57]:
x = "year"
y = ["z_f_per_fr_mv_g", "z_size_mv_g"]
plot_director_films(df, 
                    x, 
                    y, 
                    name, 
                    line=True, 
                    x_name='Year',
                    y_name='Z Score',
                    title="Christopher Nolan: Faces per Frame, Size by Year",
                    marker_labels=True,
                    width=1200,
                    height=600,
                    text_size=16,
                    dst="./plots/nolan/nolan_faces_per_frame_size_vs_year.png")

In [58]:
nolan[y].corr()

                 z_f_per_fr_mv_g  z_size_mv_g
z_f_per_fr_mv_g         1.000000    -0.667818
z_size_mv_g            -0.667818     1.000000

## Avg. Faces Per Frame, Gini By Year

In [59]:
x = "year"
y = ["z_f_per_fr_mv_g", "z_gini_mv_g"]
plot_director_films(df, 
                    x, 
                    y, 
                    name, 
                    line=True, 
                    x_name='Year',
                    y_name='Faces per Frame (Z Score)',
                    title="Christopher Nolan: Faces per Frame",
                    marker_labels=True,
                    width=1200,
                    height=600,
                    text_size=16,
                    dst="./plots/nolan/nolan_faces_per_frame_gini_vs_year.png")

In [60]:
nolan[y].corr()

                 z_f_per_fr_mv_g  z_gini_mv_g
z_f_per_fr_mv_g         1.000000    -0.802853
z_gini_mv_g            -0.802853     1.000000

## Gini, Dispersion

In [61]:
x = "year"
y = ["z_disp_mv_g", "z_gini_mv_g"]
traces_names = {"z_disp_mv_g": "Avg. Dispersion", 
                "z_gini_mv_g": "Gini"}
plot_director_films(df, 
                    x, 
                    y, 
                    name, 
                    line=True, 
                    marker_labels=True,
                    x_name='Year',
                    y_name='Z Score',
                    title="Christopher Nolan: Avg. Dispersion and Gini Score by Year",
                    dst="./plots/nolan/nolan_size_gini_by_year.png",
                    trace_names=traces_names,
                    width=1200,
                    height=600)

In [62]:
nolan[y].corr()

             z_disp_mv_g  z_gini_mv_g
z_disp_mv_g      1.00000     -0.97311
z_gini_mv_g     -0.97311      1.00000

In [63]:
df

,person_id,person_name,title,year,kind,runtime,fact_id,imdb_id,work_id,avg_size,...,z_v_density_tv,z_v_density_tv_g,z_pct_face_tv,z_pct_face_tv_g,z_v_pct_face_tv,z_v_pct_face_tv_g,z_pct_top1_tv,z_pct_top1_tv_g,z_v_pct_top1_tv,z_v_pct_top1_tv_g
0,100036,D.W. Griffith,The Avenging Conscience: or 'Thou Shalt Not Kill',1914,movie,78.0,251,3643,32807,0.0176,...,None,None,None,None,None,None,None,None,None,None
1,41611,Giovanni Pastrone,Cabiria,1914,movie,148.0,256,3740,32809,0.0056,...,None,None,None,None,None,None,None,None,None,None
2,1037794,Lois Weber,Hypocrites,1915,movie,54.0,270,4134,32812,0.0089,...,None,None,None,None,None,None,None,None,None,None
3,100036,D.W. Griffith,Judith of Bethulia,1914,movie,61.0,272,4181,32813,0.0087,...,None,None,None,None,None,None,None,None,None,None
4,1307858,Colin Campbell,The Spoilers,1914,movie,110.0,289,4630,32816,0.0101,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7633,309,Pedro Almodóvar,Dolor y gloria,2019,movie,113.0,9772,8291806,56846,0.0374,...,None,None,None,None,None,None,None,None,None,None
7634,67367,Rian Johnson,Knives Out,2019,movie,130.0,9778,8946378,56847,0.0529,...,None,None,None,None,None,None,None,None,None,None
7635,67367,Rian Johnson,Glass Onion,2022,movie,139.0,9447,11564570,56848,0.0332,...,None,None,None,None,None,None,None,None,None,None
7636,67367,Rian Johnson,Wake Up Dead Man,2025,movie,144.0,9464,14364480,56849,0.0515,...,None,None,None,None,None,None,None,None,None,None
7637,14392,Kathryn Bigelow,A House of Dynamite,2025,movie,112.0,9495,32376165,56850,0.0430,...,None,None,None,None,None,None,None,None,None,None

## Measures by Year

In [64]:
x = "year"
y = ["z_size_mv_g", "z_f_per_fr_mv_g", "z_gini_mv_g", "z_pct_top1_mv_g", "z_dist_mv_g", "z_vert_mv_g", "z_h_spread_mv_g"]
traces_names = {"z_size_mv_g": "Avg. Face Size", 
                "z_f_per_fr_mv_g": "Faces per Frame",
                "z_gini_mv_g": "Gini",
                "z_pct_top1_mv_g": "Pct. Singles",
                "z_dist_mv_g": "Distance to Center",
                "z_vert_mv_g": "Vertical Discipline",
                "z_h_spread_mv_g": "Horizontal Spread"}
plot_director_films(df, 
                    x, 
                    y, 
                    name, 
                    line=True, 
                    marker_labels=True,
                    x_name='Year',
                    y_name='Z Score',
                    title="Christopher Nolan: Measures by Year",
                    dst="./plots/nolan/nolan_measures_by_year.png",
                    trace_names=traces_names,
                    width=1200,
                    height=600)

## Percentiles

In [65]:
nolan_global_matrix = df.copy()
metrics = {"z_size_mv_g": "Face Size", "z_f_per_fr_mv_g": "Faces per Frame", "z_dist_mv_g": "Distance from Center", "z_gini_mv_g": "Gini"}
metric_names = [m + '_pct' for m in metrics.keys()]
global_ranks = df[metrics.keys()].rank(pct=True) * 100
nolan_global_matrix[list(metrics.values())] = global_ranks
nolan_global_matrix = nolan_global_matrix[nolan_global_matrix['person_name'] == "Christopher Nolan"].drop_duplicates(subset=['title'])
nolan_global_matrix = nolan_global_matrix.sort_values(by='year', ascending=True).round(2)
cols = ["title", "year"] + list(metrics.values())
await dfi.export_async(nolan_global_matrix[cols].style.hide(axis="index"), "./data/nolan/nolan_percentile_matrix.png")
nolan_global_matrix[cols]

,title,year,Face Size,Faces per Frame,Distance from Center,Gini
5268,Following,1998,94.66,0.38,0.29,99.86
7318,Memento,2000,99.86,0.35,0.17,99.74
7319,Insomnia,2002,99.73,1.40,1.77,96.03
7247,Batman Begins,2005,98.42,13.89,10.54,81.55
7326,The Prestige,2006,97.72,2.36,11.67,89.00
7249,The Dark Knight,2008,85.93,67.64,51.77,30.52
7379,Inception,2010,97.30,9.70,10.07,86.86
7378,The Dark Knight Rises,2012,53.48,59.11,28.12,59.20
7251,Interstellar,2014,90.92,1.26,0.13,99.80
7337,Dunkirk,2017,63.16,74.14,23.81,61.10
7258,Tenet,2020,76.40,2.89,1.05,99.12
6045,Oppenheimer,2023,62.86,47.81,3.06,98.02

## Box Plots

In [66]:
query = """
    SELECT
        dw.title,
        dw.year,
        ff.pct_of_frame
    FROM factFace ff
    INNER JOIN dimWork dw ON dw.imdb_id = ff.imdb_id
    INNER JOIN dimDetectionInfo di ON di.work_id = ff.work_id
    INNER JOIN bridgePerson bp ON ff.work_id = bp.work_id
    INNER JOIN dimPerson dp ON bp.person_id = dp.person_id
    INNER JOIN dimJob dj ON bp.job_id = dj.job_id
    WHERE dp.name = "Christopher Nolan"
        AND dj.job_name = "Director"
    ORDER BY dw.year ASC
"""
face_df = pd.read_sql(db.text(query), engine)
face_df

             title  year  pct_of_frame
0        Following  1998        0.0484
1        Following  1998        0.0309
2        Following  1998        0.0113
3        Following  1998        0.0119
4        Following  1998        0.0110
...            ...   ...           ...
89552  Oppenheimer  2023        0.2229
89553  Oppenheimer  2023        0.2249
89554  Oppenheimer  2023        0.2388
89555  Oppenheimer  2023        0.2511
89556  Oppenheimer  2023        0.2613

[89557 rows x 3 columns]

In [67]:
fig = px.box(face_df, 
             x="title", 
             y="pct_of_frame", 
             points="outliers", # Shows those 'Peak' faces as individual dots
             title="Nolan: Distribution of Face Sizes per Movie",
             color_discrete_sequence=["#79b8b8"])

fig.update_layout(layout)
fig.show()

## Gridmaps

In [77]:
plot_sample_grid(engine, layout=layout, plot_title="Inudstry Baseline", dst="./plots/nolan/nolan_sample_gridmap.png")

In [69]:
create_gridmap_from_director(name, engine, dst="./plots/nolan/nolan_gridmap.png", layout=layout)

In [70]:
compare_director_to_sample_grid(name, engine, layout=layout, title="Christopher Nolan vs. Industry Baseline", dst="./plots/nolan/nolan_gridmap_vs_industry_baseline.png")

## Cameras

In [71]:
query = """
    SELECT *
    FROM vwCamerasByPerson
    WHERE person_name = 'Christopher Nolan'
        AND job_name = 'Director'
"""
camera_df = pd.read_sql(query, engine)
camera_df

,person_name,camera_name,is_imax,title,year,job_name,fact_id,imdb_id,work_id,avg_size,...,z_v_density_tv,z_v_density_tv_g,z_pct_face_tv,z_pct_face_tv_g,z_v_pct_face_tv,z_v_pct_face_tv_g,z_pct_top1_tv,z_pct_top1_tv_g,z_v_pct_top1_tv,z_v_pct_top1_tv_g
0,Christopher Nolan,Arriflex 16 BL,0,Following,1998,Director,7921,154506,38765,0.0549,...,None,None,None,None,None,None,None,None,None,None
1,Christopher Nolan,"Arriflex 435 ES, Panavision Primo Lenses",0,Oppenheimer,2023,Director,9472,15398776,52517,0.0273,...,None,None,None,None,None,None,None,None,None,None
2,Christopher Nolan,"IMAX MKIII, Panavision Sphero 65 and Hasselbla...",1,Oppenheimer,2023,Director,9472,15398776,52517,0.0273,...,None,None,None,None,None,None,None,None,None,None
3,Christopher Nolan,"IMAX MKIV, Panavision Sphero 65 and Hasselblad...",1,Oppenheimer,2023,Director,9472,15398776,52517,0.0273,...,None,None,None,None,None,None,None,None,None,None
4,Christopher Nolan,"IMAX MSM 9802, Panavision Sphero 65 and Hassel...",1,Oppenheimer,2023,Director,9472,15398776,52517,0.0273,...,None,None,None,None,None,None,None,None,None,None
5,Christopher Nolan,"Panavision Panaflex System 65 Studio, Panavisi...",0,Oppenheimer,2023,Director,9472,15398776,52517,0.0273,...,None,None,None,None,None,None,None,None,None,None
6,Christopher Nolan,"Panavision Panaflex Platinum, Panavision C- an...",0,Batman Begins,2005,Director,8434,372784,55443,0.0726,...,None,None,None,None,None,None,None,None,None,None
7,Christopher Nolan,"Arriflex 435, Panavision Primo, C- and E-Serie...",0,Batman Begins,2005,Director,8434,372784,55443,0.0726,...,None,None,None,None,None,None,None,None,None,None
8,Christopher Nolan,"Panavision Panaflex Millennium XL, Panavision ...",0,Batman Begins,2005,Director,8434,372784,55443,0.0726,...,None,None,None,None,None,None,None,None,None,None
9,Christopher Nolan,"Bell & Howell Eyemo, Panavision C- and E-Serie...",0,Batman Begins,2005,Director,8434,372784,55443,0.0726,...,None,None,None,None,None,None,None,None,None,None
10,Christopher Nolan,"Panavision Panaflex Platinum, Panavision C-, E...",0,The Dark Knight,2008,Director,8390,468569,55458,0.0410,...,None,None,None,None,None,None,None,None,None,None
11,Christopher Nolan,"Beaumont VistaVision Camera, Panavision Primo ...",0,The Dark Knight,2008,Director,8390,468569,55458,0.0410,...,None,None,None,None,None,None,None,None,None,None
12,Christopher Nolan,"IMAX MKIII, Hasselblad Lenses",1,The Dark Knight,2008,Director,8390,468569,55458,0.0410,...,None,None,None,None,None,None,None,None,None,None
13,Christopher Nolan,"IMAX MSM 9802, Hasselblad Lenses",1,The Dark Knight,2008,Director,8390,468569,55458,0.0410,...,None,None,None,None,None,None,None,None,None,None
14,Christopher Nolan,"Panavision Panaflex Millennium XL, Panavision ...",0,The Dark Knight,2008,Director,8390,468569,55458,0.0410,...,None,None,None,None,None,None,None,None,None,None
15,Christopher Nolan,"Beaumont VistaVision Camera, Leica Lenses",0,Interstellar,2014,Director,8269,816692,55469,0.0471,...,None,None,None,None,None,None,None,None,None,None
16,Christopher Nolan,"IMAX MSM 9802, Hasselblad and Mamiya Lenses",1,Interstellar,2014,Director,8269,816692,55469,0.0471,...,None,None,None,None,None,None,None,None,None,None
17,Christopher Nolan,"Panavision Panaflex Millennium XL2, Panavision...",0,Interstellar,2014,Director,8269,816692,55469,0.0471,...,None,None,None,None,None,None,None,None,None,None
18,Christopher Nolan,"IMAX MKIII, Panavision Sphero 65 and Hasselbla...",1,Tenet,2020,Director,9741,6723592,55497,0.0333,...,None,None,None,None,None,None,None,None,None,None
19,Christopher Nolan,"IMAX MKIV, Panavision Sphero 65 and Hasselblad...",1,Tenet,2020,Director,9741,6723592,55497,0.0333,...,None,None,None,None,None,None,None,None,None,None
20,Christopher Nolan,"IMAX MSM 9802, Panavision Sphero 65 and Hassel...",1,Tenet,2020,Director,9741,6723592,55497,0.0333,...,None,None,None,None,None,None,None,None,None,None
21,Christopher Nolan,"Arriflex 765, Panavision Sphero 65 Lenses",0,Tenet,2020,Director,9741,6723592,55497,0.0333,...,None,None,None,None,None,None,None,None,None,None
22,Christopher Nolan,Beaumont VistaVision Camera,0,Tenet,2020,Director,9741,6723592,55497,0.0333,...,None,None,None,None,None,None,None,None,None,None
23,Christopher Nolan,"Logmar Magellan, Panavision Sphero 65 Lenses",0,Tenet,2020,Director,9741,6723592,55497,0.0333,...,None,None,None,None,None,None,None,None,None,None
24,Christopher Nolan,"Panavision Panaflex System 65 Studio, Panavisi...",0,Tenet,2020,Director,9741,6723592,55497,0.0333,...,None,None,None,None,None,None,None,None,None,None
25,Christopher Nolan,"Panavision Panaflex Gold II, Panavision E-Seri...",0,Memento,2000,Director,7215,209144,56020,0.1105,...,None,None,None,None,None,None,None,None,None,None
26,Christopher Nolan,"Panavision Panaflex Millennium XL, Panavision ...",0,Insomnia,2002,Director,8073,278504,56094,0.0987,...,None,None,None,None,None,None,None,None,None,None
27,Christopher Nolan,"Panavision Panaflex Platinum, Panavision Primo...",0,Insomnia,2002,Director,8073,278504,56094,0.0987,...,None,None,None,None,None,None,None,None,None,None
28,Christopher Nolan,"Aaton 35-III, Panavision C-Series Lenses",0,Insomnia,2002,Director,8073,278504,56094,0.0987,...,None,None,None,None,None,None,None,None,None,None
29,Christopher Nolan,"Panavision Panaflex Millennium XL2, Panavision...",0,The Prestige,2006,Director,8222,482571,56162,0.0679,...,None,None,None,None,None,None,None,None,None,None
30,Christopher Nolan,Spacecam Aerial Cameras,0,The Prestige,2006,Director,8222,482571,56162,0.0679,...,None,None,None,None,None,None,None,None,None,None
31,Christopher Nolan,"IMAX MKIV, Panavision Sphero 65 and Hasselblad...",1,Dunkirk,2017,Director,9698,5013056,56222,0.0274,...,None,None,None,None,None,None,None,None,None,None
32,Christopher Nolan,"IMAX MSM 9802, Panavision Sphero 65 and Hassel...",1,Dunkirk,2017,Director,9698,5013056,56222,0.0274,...,None,None,None,None,None,None,None,None,None,None
33,Christopher Nolan,"Panavision Panaflex System 65 Studio, Panavisi...",0,Dunkirk,2017,Director,9698,5013056,56222,0.0274,...,None,None,None,None,None,None,None,None,None,None
34,Christopher Nolan,"Panavision 65 HR Camera, Panavision Sphero 65 ...",0,Dunkirk,2017,Director,9698,5013056,56222,0.0274,...,None,None,None,None,None,None,None,None,None,None
35,Christopher Nolan,"Panavision Panaflex System 65 Studio, Panavisi...",0,The Dark Knight Rises,2012,Director,8820,1345836,56548,0.0242,...,None,None,None,None,None,None,None,None,None,None
36,Christopher Nolan,"Arriflex 235, Panavision C-, E-Series and Supe...",0,The Dark Knight Rises,2012,Director,8820,1345836,56548,0.0242,...,None,None,None,None,None,None,None,None,None,None
37,Christopher Nolan,"Panavision Panaflex Millennium XL2, Panavision...",0,The Dark Knight Rises,2012,Director,8820,1345836,56548,0.0242,...,None,None,None,None,None,None,None,None,None,None
38,Christopher Nolan,"Beaumont VistaVision Camera, Panavision Primo ...",0,The Dark Knight Rises,2012,Director,8820,1345836,56548,0.0242,...,None,None,None,None,None,None,None,None,None,None
39,Christopher Nolan,"IMAX MSM 9802, Hasselblad and Mamiya Lenses",1,The Dark Knight Rises,2012,Director,8820,1345836,56548,0.0242,...,None,None,None,None,None,None,None,None,None,None
40,Christopher Nolan,"Panavision Panaflex Gold II, Panavision C-, E-...",0,The Dark Knight Rises,2012,Director,8820,1345836,56548,0.0242,...,None,None,None,None,None,None,None,None,None,None
41,Christopher Nolan,"Panavision Panaflex System 65 Studio, Panavisi...",0,Inception,2010,Director,8825,1375666,56549,0.0650,...,None,None,None,None,None,None,None,None,None,None
42,Christopher Nolan,"Beaumont VistaVision Camera, Panavision Primo ...",0,Inception,2010,Director,8825,1375666,56549,0.0650,...,None,None,None,None,None,None,None,None,None,None
43,Christopher Nolan,"Arriflex 235, Panavision Primo and G-Series Le...",0,Inception,2010,Director,8825,1375666,56549,0.0650,...,None,None,None,None,None,None,None,None,None,None
44,Christopher Nolan,"Arriflex 435 ES, Panavision Primo and G-Series...",0,Inception,2010,Director,8825,1375666,56549,0.0650,...,None,None,None,None,None,None,None,None,None,None
45,Christopher Nolan,"Panavision 65 HR Camera, Panavision System 65 ...",0,Inception,2010,Director,8825,1375666,56549,0.0650,...,None,None,None,None,None,None,None,None,None,None
46,Christopher Nolan,"Panavision Panaflex Millennium XL, Panavision ...",0,Inception,2010,Director,8825,1375666,56549,0.0650,...,None,None,None,None,None,None,None,None,None,None
47,Christopher Nolan,"Photo-Sonics 4C, Panavision Primo Lenses",0,Inception,2010,Director,8825,1375666,56549,0.0650,...,None,None,None,None,None,None,None,None,None,None
48,Christopher Nolan,"Photo-Sonics 4ER, Panavision Primo Lenses",0,Inception,2010,Director,8825,1375666,56549,0.0650,...,None,None,None,None,None,None,None,None,None,None

In [72]:
y = ["z_size_mv_g", "z_f_per_fr_mv_g", "z_gini_mv_g", "z_dist_mv_g"]

names = {
    "z_size_mv_g": "Avg. Size",
    "z_f_per_fr_mv_g": "Avg. Faces per Frame",
    "z_gini_mv_g": "Avg. Gini",
    "z_dist_mv_g": "Avg. Distance",
}

camera_g = camera_df[y + ["is_imax"]].groupby('is_imax').mean()
camera_g = camera_g.rename(names, axis=1)
camera_g.round(2)

         Avg. Size  Avg. Faces per Frame  Avg. Gini  Avg. Distance
is_imax
0             1.79                 -0.83       1.32          -1.47
1             0.36                 -0.42       1.43          -1.51

In [73]:
styled_table = (
    camera_g
    .style
    .format(precision=2)  # This is the key line for the image export
)

await dfi.export_async(styled_table, "./data/nolan/nolan_camera_matrix.png")

In [74]:
query = """
    SELECT 
        is_imax,
        ROUND(AVG(z_size_mv_g), 2) AS `Avg. Size`,
        ROUND(AVG(z_f_per_fr_mv_g), 2) AS `Avg. Faces per Frame`,
        ROUND(AVG(z_gini_mv_g), 2) AS `Avg. Gini`,
        ROUND(AVG(z_dist_mv_g), 2) AS `Avg. Distance`
    FROM factWork fw 
    INNER JOIN bridgeCamera bc ON fw.work_id = bc.work_id
    INNER JOIN dimCamera dc ON bc.camera_id = dc.camera_id
    GROUP BY is_imax
"""
camera_sample = pd.read_sql(query, engine)
camera_sample

   is_imax  Avg. Size  Avg. Faces per Frame  Avg. Gini  Avg. Distance
0        0       0.72                 -0.15      -0.08          -0.35
1        1       0.53                 -0.71       1.24          -1.44

In [75]:
styled_table = (
    camera_sample
    .style
    .format(precision=2)  # This is the key line for the image export
)

await dfi.export_async(styled_table, "./data/nolan/nolan_sample_camera_matrix.png")

## Personnel

In [78]:
query = """
    WITH nolan AS (
        SELECT work_id 
        FROM `vwWorksByPerson`
        WHERE person_name = "Christopher Nolan"
            AND job_name = "Director"
    )
    SELECT 
        person_name,
        ROUND(AVG(z_size_mv_g), 2) AS `Avg. Face Size`,
        ROUND(AVG(z_f_per_fr_mv_g), 2) AS `Avg. Faces per Frame`,
        ROUND(AVG(z_vert_mv_g), 2) AS `Vertical Discipline`,
        ROUND(AVG(z_gini_mv_g), 2) AS `Gini`,
        ROUND(AVG(z_dist_mv_g), 2) AS `Avg. Distance`
    FROM `vwWorksByPerson` wbp
    INNER JOIN nolan n ON n.work_id = wbp.work_id
    WHERE person_name IN ("Wally Pfister", "Hoyte van Hoytema") AND wbp.work_id IN (n.work_id)
    GROUP BY person_name
"""
cinematographer_df = pd.read_sql(query, engine)
cinematographer_df

,person_name,Avg. Face Size,Avg. Faces per Frame,Vertical Discipline,Gini,Avg. Distance
0,Wally Pfister,2.41,-0.80,-0.15,1.02,-1.26
1,Hoyte van Hoytema,0.45,-0.68,1.23,2.06,-2.08

In [ ]:
styled_table = (
    cinematographer_df
    .style
    .format(precision=2)  # This is the key line for the image export
)

await dfi.export_async(styled_table, "./data/nolan/nolan_cinematographers.png")