In [1]:
import os
import sys

import numpy as np
import pandas as pd
import plotly.express as px
import dataframe_image as dfi
import plotly.graph_objects as go
from scipy import stats 
import sqlalchemy as db

sys.path.append(os.path.abspath(os.path.join('../..')))

from utils import *

In [2]:
username = "amos"
password = "M0$hicat"
host = "192.168.0.131"
port = "3306"
database = "CineFaceDW"
connection_string = f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}'
engine = db.create_engine(connection_string)

In [6]:
name = "Wong Kar-Wai"

In [7]:
df = pd.read_sql(f"SELECT * FROM vwWorksByDirector WHERE kind = 'movie'", engine)
df

,person_id,person_name,title,year,kind,runtime,fact_id,imdb_id,work_id,avg_size,...,z_v_density_tv,z_v_density_tv_g,z_pct_face_tv,z_pct_face_tv_g,z_v_pct_face_tv,z_v_pct_face_tv_g,z_pct_top1_tv,z_pct_top1_tv_g,z_v_pct_top1_tv,z_v_pct_top1_tv_g
0,100036,D.W. Griffith,The Avenging Conscience: or 'Thou Shalt Not Kill',1914,movie,78.0,251,3643,32807,0.0176,...,None,None,None,None,None,None,None,None,None,None
1,41611,Giovanni Pastrone,Cabiria,1914,movie,148.0,256,3740,32809,0.0056,...,None,None,None,None,None,None,None,None,None,None
2,1037794,Lois Weber,Hypocrites,1915,movie,54.0,270,4134,32812,0.0089,...,None,None,None,None,None,None,None,None,None,None
3,100036,D.W. Griffith,Judith of Bethulia,1914,movie,61.0,272,4181,32813,0.0087,...,None,None,None,None,None,None,None,None,None,None
4,1307858,Colin Campbell,The Spoilers,1914,movie,110.0,289,4630,32816,0.0101,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7642,309,Pedro Almodóvar,Dolor y gloria,2019,movie,113.0,9772,8291806,56846,0.0374,...,None,None,None,None,None,None,None,None,None,None
7643,67367,Rian Johnson,Knives Out,2019,movie,130.0,9778,8946378,56847,0.0529,...,None,None,None,None,None,None,None,None,None,None
7644,67367,Rian Johnson,Glass Onion,2022,movie,139.0,9447,11564570,56848,0.0332,...,None,None,None,None,None,None,None,None,None,None
7645,67367,Rian Johnson,Wake Up Dead Man,2025,movie,144.0,9464,14364480,56849,0.0515,...,None,None,None,None,None,None,None,None,None,None
7646,14392,Kathryn Bigelow,A House of Dynamite,2025,movie,112.0,9495,32376165,56850,0.0430,...,None,None,None,None,None,None,None,None,None,None

In [8]:
g = pd.read_sql("SELECT * FROM vwDirectorStats WHERE cnt > 5", engine)
g

,person_id,name,cnt,avg_f_per_fr,z_size_mv_mean,z_size_mv_g_mean,z_size_mv_std,z_size_mv_g_std,z_top1_mv_mean,z_top1_mv_g_mean,...,z_v_density_mv_mean,z_v_density_mv_g_mean,z_pct_top1_mv_mean,z_pct_top1_mv_g_mean,z_v_pct_top1_mv_mean,z_v_pct_top1_mv_g_mean,z_pct_face_mv_mean,z_pct_face_mv_g_mean,z_v_pct_face_mv_mean,z_v_pct_face_mv_g_mean
0,1,George Lucas,6,1.597648,-0.053352,0.814914,0.783111,0.766601,-0.190065,0.802465,...,0.000000,0.000000,0.277344,0.991328,-0.111087,-0.397079,-0.226912,0.660440,-0.229422,0.845807
1,40,Orson Welles,9,1.770517,0.697528,0.110828,0.808529,0.445027,0.889053,0.204514,...,0.745900,0.449870,0.888112,0.327788,0.070874,0.214835,0.630211,0.140793,1.023617,0.451762
2,68,Fritz Lang,33,1.873031,-0.432220,-0.640721,0.738070,0.369027,-0.447708,-0.691414,...,0.064489,-0.170618,0.384600,-0.147534,0.320935,0.367024,-0.660249,-0.775029,-0.107610,-0.558840
3,138,Quentin Tarantino,7,1.581424,-0.217380,0.863364,0.969357,1.334367,-0.287119,0.842447,...,-0.286160,0.325392,0.116981,1.032773,-0.151320,-0.850129,-0.378893,0.631704,0.342752,1.289849
4,190,Clint Eastwood,32,2.017244,-0.416212,0.314150,0.702603,0.667530,-0.269060,0.586161,...,0.029670,0.063425,-0.578839,0.328151,0.495116,0.198262,-0.136572,0.651149,-0.389156,0.490620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,940663,Chester M. Franklin,8,1.618405,0.397221,-0.568999,0.979921,0.185540,0.344414,-0.740273,...,-0.017444,0.621329,-0.074203,0.162069,0.396381,0.419476,0.359364,-0.866964,-0.004262,-0.903669
329,1021685,E. Mason Hopper,6,1.722700,-0.272303,-0.544496,0.875573,0.382297,-0.368806,-0.691033,...,-0.234674,-0.300615,-0.142999,-0.409118,0.188546,0.391993,-0.542793,-0.771631,-0.404528,-0.799606
330,1036754,Reginald Barker,7,1.812715,0.462617,-0.635704,0.387553,0.375400,0.511501,-0.746425,...,0.359743,0.539909,-0.135964,-0.138941,0.476722,0.568228,0.635482,-0.770480,0.400587,-0.831591
331,1065336,Melville W. Brown,6,1.830765,-0.722426,-0.799145,0.455469,0.263664,-0.791800,-0.919072,...,-0.030822,-0.239791,-0.170180,-0.596750,0.235600,0.280355,-0.923024,-0.982991,-0.877001,-1.104247
332,1225777,Leigh Jason,7,2.091450,0.035561,-0.406215,0.444228,0.174203,0.024545,-0.447347,...,0.075440,-0.314887,-0.587623,-0.964119,-0.176007,0.104267,0.400758,-0.178973,0.090061,-0.432101

In [10]:
x = "z_size_mv_g_mean"
y = "z_v_size_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name], 
                              x_title="Avg. Size (Z Score)", 
                              y_title="Size Variance (Z Score)", 
                              title="Wong Kar-Wai: Avg. Face Size vs. Std. Face Size", 
                              width=1200,
                              height=600,
                              dst="./plots/wong_kar_wai/wong_kar_wai_size_v_variance.png")

In [12]:
x = "z_f_per_fr_mv_g_mean"
y = "z_size_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title=f"{name}: Avg. Faces per Frame vs. Avg. Face Size",
                              x_title="Avg. Faces per Frame (Z Score)",
                              y_title="Avg. Face Size (Z Score)",
                              dst="./plots/wong_kar_wai/wong_kar_wai_faces_per_fr_vs_avg_size.png",
                              width=1200,
                              height=600)

In [13]:
x = "z_f_per_fr_mv_g_mean"
y = "z_pct_top1_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title=f"{name}: Avg. Faces per Frame vs. Pct. Singles",
                              x_title="Avg. Faces per Frame (Z Score)",
                              y_title="% Singles (Z Score)",
                              dst="./plots/wong_kar_wai/wong_kar_wai_faces_per_fr_vs_singles.png",
                              width=1200,
                              height=600)

In [14]:
x = "z_f_per_fr_mv_g_mean"
y = "z_disp_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title=f"{name}: Faces per Frame vs. Dispersion",
                              width=1200,
                              height=600,
                              x_title="Faces per Frame (Z Score)",
                              y_title="Dispersion (Z Score)",
                              dst="./plots/wong_kar_wai/wong_kar_wai_f_per_fr_vs_disp.png"
                              )

In [15]:
x = "z_dist_mv_g_mean"
y = "z_v_dist_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title=f"{name}: Avg. Distance from Center vs. Std. Distance from Center",
                              x_title="Avg. Distance from Center (Z Score)",
                              y_title="Std. Distance from Center (Z Score)",
                              dst="./plots/wong_kar_wai/wong_kar_wai_avg_dist_vs_std_dist.png",
                              width=1200,
                              height=600)

In [16]:
x = "z_disp_mv_g_mean"
y = "z_gini_mv_g_mean"
plot_directors_against_sample(g, 
                              x, 
                              y, 
                              [name],
                              title=f"{name}: Dispersion vs. Gini",
                              x_title="Dispersion (Z Score)",
                              y_title="Gini (Z Score)",
                              dst="./plots/wong_kar_wai/wong_kar_wai_disp_vs_gini.png",
                              width=1200,
                              height=600)