## Imports and Functions

In [2]:
from pathlib import Path 

import cv2
import IPython
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objs as go

In [3]:
def drop_duplicates(df):
    to_drop = []
    for name in df['name'].unique():
        t = df[df['name'] == name]
        for idx, row in t.iterrows():
            for i, r in t.iterrows():
                if (r['y1'] > row['y1'] and r['y1'] < row['y1']) and \
                (r['y2'] > row['y1'] and r['y2'] < row['y2']):
                    to_drop.append(row['name'])
    return list(set(to_drop))

    # to_drop = []
    # for name in dlib_status['name'].unique():
    #     t = dlib_status[dlib_status['name'] == name]
    #     for idx, row in t.iterrows():
    #         for i, r in t.iterrows():
    #             if (r['x1'] > row['x1'] and r['x1'] < row['x2']) and \
    #             (r['x2'] > row['x1'] and r['x2'] < row['x2']) and \
    #             (r['y1'] > row['y1'] and r['y1'] < row['y1']) and \
    #             (r['y2'] > row['y1'] and r['y2'] < row['y2']):
    #                 to_drop.append(row['name'])
    # list(set(to_drop))

In [4]:
def compare_faces(source, 
                  faces):
    temp = faces.rename({'x1': 'x1_ground',
            'y1': 'y1_ground',
            'x2': 'x2_ground',
            'y2': 'y2_ground',
            'width': 'width_ground',
            'height': 'height_ground'}, axis=1)
    temp = temp[['x1_ground',
                    'y1_ground',
                    'x2_ground',
                    'y2_ground',
                    'width_ground',
                    'height_ground',
                    'face_num',
                    'name']]

    df = source.merge(temp,
                on=['name', 'face_num'],
                how='left')
    df['status'] = df.apply(lambda x: 'tp' if pd.notna(x['x1_ground']) else 'fp', axis=1)

    rdf = temp.merge(df.drop(['x1_ground', 'y1_ground', 'x2_ground', 'y2_ground', 'width_ground', 'height_ground'], axis=1),
                 on=['name', 'face_num'],
                 how='left')
    rdf['status'] = rdf.apply(lambda x: 'fn' if pd.isna(x['x1']) else np.nan, axis=1)
    fn = rdf[rdf['x1'].isna()]

    df = pd.concat([df, fn], axis=0)
    
    # df['center_x'] = df.apply(lambda x: x['x1'] + int(x['width']/2), axis=1)
    # df['center_y'] = df.apply(lambda x: x['y1'] + int(x['height']/2), axis=1)
    # df['center_ground_x'] = df.apply(lambda x: x['x1_ground'] + int(x['width_ground']/2), axis=1)
    # df['center_ground_y'] = df.apply(lambda x: x['y1_ground'] + int(x['height_ground']/2), axis=1)
    
    return df

In [5]:
def show_image(image):
    _, ret = cv2.imencode('.jpg', image)
    i = IPython.display.Image(data=ret)
    IPython.display.display(i)

In [6]:
def show_by_id(id):
    faces = pd.read_csv('../data/faces.csv', index_col=0)
    fp = Path('../test_images').joinpath(faces.iloc[id]['name'])
    img = cv2.imread(str(fp))
    print(fp.name)
    show_image(img)

In [7]:
def show_correct_by_id(id, df):
    temp = df[(df['id'] == id) & (df['x1'].notna())]
    return temp['detector']

In [8]:
def show_by_name(name):
    fp = Path('../test_images').joinpath(name)
    img = cv2.imread(str(fp))
    show_image(img)

In [9]:
def show_heatmap(df):
    g = df[['status', 'name']].groupby('status').count()
    d = {'tp': round(g.loc['tp'].item()/g['name'].sum(), 3),
         'fp': round(g.loc['fp'].item()/g['name'].sum(), 3),
         'fn': round(g.loc['fn'].item()/g['name'].sum(), 3),
         'tn': 0}
    a = [[d['tp'], d['fp']], [d['fn'], d['tn']]]
    text = [[f'True Positive: {d["tp"]} ({g.loc["tp"].item()}/{g["name"].sum()})',
             f'False Positive: {d["fp"]} ({g.loc["fp"].item()}/{g["name"].sum()})'],
            [f'False Negative: {d["fn"]} ({g.loc["fn"].item()}/{g["name"].sum()})',
             f'True Negative: {d["tn"]} (0/{g["name"].sum()})']]
    fig = px.imshow(a, 
                    x=['positive', 'negative'],
                    y=['positive', 'negative'],
                    labels={'y': 'Predicted', 'x': 'Actual'})
    fig.update_traces(text=text, texttemplate="%{text}")
    fig.show()

## Loading the Data

In [10]:
faces = pd.read_csv('../data/faces.csv', index_col=0)
print(faces.shape)
faces.head()

(1895, 12)

,name,img_height,img_width,x1,y1,x2,y2,width,height,area,pct_of_frame,face_num
0,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png,1080,1920,323,5,919,731,596,726,432696,0.208669,0
1,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png,1080,1920,262,42,614,507,352,465,163680,0.078935,0
2,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,484,389,671,617,187,228,42636,0.020561,0
3,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,1003,42,1195,261,192,219,42048,0.020278,1
4,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png,1080,1920,1121,66,1662,824,541,758,410078,0.197761,0

In [11]:
dlib_df = pd.read_csv('../test_results/dlib_new.csv', index_col=0)
print(dlib_df.shape)
dlib_df.head()

(1203, 13)

,x1,y1,x2,y2,width,height,area,confidence,face_num,img_width,img_height,pct_of_frame,name
0,530,251,938,659,408,408,166464,1.156534,0,1920,1080,0.080278,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png
1,239,181,522,464,283,283,80089,1.043341,0,1920,1080,0.038623,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png
2,546,450,683,586,137,136,18632,0.667519,0,1920,1080,0.008985,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
3,996,109,1110,223,114,114,12996,0.637119,1,1920,1080,0.006267,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
4,1045,296,1534,785,489,489,239121,1.075798,0,1920,1080,0.115317,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png

In [12]:
retina_df = pd.read_csv('../test_results/retina_new.csv', index_col=0)
# retina_df = retina_df.groupby(['name', 'face_num']).max()
# retina_df = retina_df.reset_index()
retina_df.head()

,x1,y1,x2,y2,width,height,area,confidence,face_num,img_width,img_height,pct_of_frame,name
0,534,190,926,712,392,522,204624,0.999803,0,1920,1080,0.098681,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png
1,276,104,528,491,252,387,97524,0.999671,0,1920,1080,0.047031,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png
2,1002,81,1107,262,105,181,19005,0.999594,0,1920,1080,0.009165,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
3,543,411,668,598,125,187,23375,0.999471,1,1920,1080,0.011273,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
4,660,276,676,296,16,20,320,0.965943,2,1920,1080,0.000154,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png

In [13]:
torch_df = pd.read_csv('../test_results/torch.csv', index_col=0)
torch_df.head()

,x1,y1,x2,y2,width,height,area,confidence,face_num,img_width,img_height,pct_of_frame,name
0,544,207,913,698,369,491,181179,698.003601,0,1920,1080,0.087374,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png
1,263,162,500,455,237,293,69441,455.585022,0,1920,1080,0.033488,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png
2,1114,225,1560,821,446,596,265816,821.530823,0,1920,1080,0.128191,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png
3,493,227,805,645,312,418,130416,645.647217,0,1920,1080,0.062894,Billions.S02E07.1080p.BluRay.x265-RARBG_69600.png
4,501,93,916,696,415,603,250245,696.220093,0,1920,1080,0.120681,Billions.S03E05.1080p.WEBRip.x265-RARBG_77832.png

In [14]:
cv_df = pd.read_csv('../test_results/cv.csv', index_col=0)
cv_df.head()

,x1,y1,x2,y2,img_width,img_height,width,height,area,pct_of_frame,confidence,face_num,id,name
0,522,167,912,681,1920,1080,390,514,200460,0.096672,0.995575,0,0,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png
1,276,113,505,477,1920,1080,229,364,83356,0.040199,0.942709,0,1,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png
2,1119,182,1542,799,1920,1080,423,617,260991,0.125864,0.999954,0,4,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png
3,970,207,1347,848,1920,1080,377,641,241657,0.116540,0.999548,0,5,Billions.S02E01.1080p.BluRay.x265-RARBG_32328.png
4,766,129,1200,749,1920,1080,434,620,269080,0.129765,0.995495,0,6,Billions.S02E07.1080p.BluRay.x265-RARBG_39816.png

In [15]:
batchface_df = pd.read_csv('../test_results/batchface.csv', index_col=0)
batchface_df.head()

,x1,y1,x2,y2,width,height,area,confidence,face_num,img_width,img_height,pct_of_frame,name,duration
0,534,157,923,722,389,565,219785,0.999868,0,1920,1080,0.105992,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png,2.901
1,276,127,524,490,248,363,90024,0.999628,0,1920,1080,0.043414,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png,0.133
2,1002,76,1099,258,97,182,17654,0.997610,0,1920,1080,0.008514,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,0.143
3,535,396,664,601,129,205,26445,0.997312,1,1920,1080,0.012753,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,0.143
4,661,275,678,298,17,23,391,0.969282,2,1920,1080,0.000189,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,0.143

In [29]:
custom_df = pd.read_csv('../test_results/retina_custom_120.csv', index_col=0)
custom_df.head()

,x1,y1,x2,y2,width,height,area,confidence,face_num,img_width,img_height,pct_of_frame,name
0,59,19,102,79,43,60,2580,0.999794,0,1920,1080,0.001244,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png
1,30,11,58,54,28,43,1204,0.999600,0,1920,1080,0.000581,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png
2,60,47,74,66,14,19,266,0.999224,0,1920,1080,0.000128,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
3,111,9,123,27,12,18,216,0.994894,1,1920,1080,0.000104,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
4,123,22,172,90,49,68,3332,0.999045,0,1920,1080,0.001607,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png

## Comparing the Models

### Dlib

In [117]:
dlib_status = compare_faces(dlib_df, faces)

In [116]:
show_heatmap(dlib_status)

### RetinaFace

In [17]:
retina_status = compare_faces(retina_df, faces)
show_heatmap(retina_status)

#### Analysis

In [122]:
fig = px.histogram(retina_status, x='pct_of_frame', color='status', histnorm='percent')
fig.show()

In [123]:
fig = px.scatter(retina_status, x='pct_of_frame', y='confidence')
fig.show()

In [124]:
g = retina_status[['status', 'confidence']].groupby('status').mean()
fig = px.bar(g, x=g.index, y='confidence')
fig.show()

In [125]:
g = retina_status[['status', 'pct_of_frame']].groupby('status').mean()
fig = px.bar(g, x=g.index, y='pct_of_frame')
fig.show()

#### False Positives

In [24]:
temp = retina_status[retina_status['status'] == 'fp']['name'].unique().tolist()
print(len(temp))
[print(x) for x in temp]

103
Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
Cheers.S02E06.1080p.BluRay.x265-RARBG_24360.png
Cheers.S03E05.1080p.BluRay.x265-RARBG_33960.png
Cheers.S03E05.1080p.BluRay.x265-RARBG_34080.png
Cheers.S03E06.1080p.BluRay.x265-RARBG_31200.png
Cheers.S03E07.1080p.BluRay.x265-RARBG_16704.png
Cheers.S03E18.1080p.BluRay.x265-RARBG_31848.png
Cheers.S03E25.1080p.BluRay.x265-RARBG_13920.png
Cheers.S04E15.1080p.BluRay.x265-RARBG_01104.png
Cheers.S04E23.1080p.BluRay.x265-RARBG_14064.png
Cheers.S05E21.1080p.BluRay.x265-RARBG_06696.png
Cheers.S06E08.1080p.BluRay.x265-RARBG_00120.png
Cheers.S06E09.1080p.BluRay.x265-RARBG_26112.png
Cheers.S06E20.1080p.BluRay.x265-RARBG_30912.png
Cheers.S06E22.1080p.BluRay.x265-RARBG_30504.png
Cheers.S07E08.1080p.BluRay.x265-RARBG_06768.png
Cheers.S08E19.1080p.BluRay.x265-RARBG_28848.png
Cheers.S09E06.1080p.BluRay.x265-RARBG_23304.png
Cheers.S09E23.1080p.BluRay.x265-RARBG_06960.png
Cheers.S10E19.1080p.BluRay.x265-RARBG_16776.png
Cheers.S11E13.1080p.BluRay.x265-RARBG_24672.png
Frasier.S03E19.Crane.vs.Crane.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_14784.png
Frasier.S04E05.Head.Game.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_02184.png
Frasier.S04E22.Are.You.Being.Served.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_07320.png
Frasier.S05E16.Beware.of.Greeks.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_11448.png
Frasier.S06E05.First.Do.No.Harm.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_03000.png
Frasier.S10E13.Lilith.Needs.a.Favor.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_21936.png
Frasier.S11E08.Murder.Most.Maris.2.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_13320.png
Frasier.S11E10.Seabee.Jeebies.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_27816.png
Legion.S03E06.1080p.WEBRip.x265-RARBG_50808.png
Lost.Girl.S02E16.Schools.Out.BluRay.10Bit.1080p.DD5.1.H265-d3g_35400.png
Lost.Girl.S04E01.In.Memoriam.BluRay.10Bit.1080p.DD5.1.H265-d3g_40080.png
Modern.Family.S02E13.1080p.BluRay.x265-RARBG_19584.png
Modern.Family.S03E06.1080p.BluRay.x265-RARBG_21504.png
Modern.Family.S03E11.1080p.BluRay.x265-RARBG_15072.png
Modern.Family.S05E05.The.Late.Show.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_28104.png
Modern.Family.S05E13.Three.Dinners.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_15480.png
Modern.Family.S05E24.The.Wedding.Part.2.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_28800.png
Modern.Family.S06E12.The.Big.Guns.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_02976.png
Modern.Family.S06E16.Connection.Lost.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_04320.png
Modern.Family.S06E17.Closet.Youll.Love.It.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_26688.png
Modern.Family.S06E19.Grill.Interrupted.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_12000.png
Modern.Family.S07E13.Thunk.in.the.Trunk.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_16128.png
Modern.Family.S07E14.The.Storm.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_22272.png
Modern.Family.S07E15.I.Dont.Know.How.She.Does.It.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_06144.png
Modern.Family.S09E22.Clash.of.Swords.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_16632.png
Modern.Family.S10E04.Torn.Between.Two.Lovers.1080p.DSNP.WEB-DL.DDP5.1.H.264-OLDFAMiLY_11904.png
Party Down (2009) - S01E02 - California College Conservative Union Caucus (1080p AMZN WEBRip x265 Panda)_15720.png
Scrubs S03E14 My Screw Up  [1080p x265 10bit Joy]_05952.png
Scrubs S04E10 My Female Trouble  [1080p x265 10bit Joy]_11712.png
Scrubs S04E17 My Life In Four Cameras (c)  [1080p x265 10bit Joy]_28080.png
Scrubs S05E10 Her Story II  [1080p x265 10bit Joy]_24600.png
Scrubs S05E23 My Urologist  [1080p x265 10bit Joy]_32952.png
Scrubs S06E20 My Conventional Wisdom  [1080p x265 10bit Joy]_22704.png
Scrubs S06E20 My Conventional Wisdom  [1080p x265 10bit Joy]_39912.png
Scrubs S07E03 My Inconvenient Truth  [1080p x265 10bit Joy]_03096.png
Scrubs S07E05 My Growing Pains  [1080p x265 10bit Joy]_06936.png
Scrubs S07E05 My Growing Pains  [1080p x265 10bit Joy]_25608.png
Scrubs S08E19 My Finale Part 2  [1080p x265 10bit Joy]_20088.png
Scrubs S08E19 My Finale Part 2  [1080p x265 10bit Joy]_27144.png
Scrubs S09E05 Our Mysteries  [1080p x265 10bit Joy]_03432.png
Scrubs S09E05 Our Mysteries  [1080p x265 10bit Joy]_24360.png
Seinfeld.S01E01.1080p.WEBRip.x265-RARBG_27912.png
Seinfeld.S03E10.1080p.WEBRip.x265-RARBG_31464.png
Seinfeld.S04E08.1080p.WEBRip.x265-RARBG_09048.png
Seinfeld.S04E12.1080p.WEBRip.x265-RARBG_13560.png
Seinfeld.S05E13.1080p.WEBRip.x265-RARBG_25896.png
Seinfeld.S05E17.1080p.WEBRip.x265-RARBG_12648.png
Seinfeld.S09E12.1080p.WEBRip.x265-RARBG_29304.png
Suits.S05E11.1080p.BluRay.x265-RARBG_39696.png
Suits.S06E15.1080p.BluRay.x265-RARBG_42504.png
Ted.Lasso.S02E04.Carol.of.the.Bells.AAC.5.1.1080p.WEBRip.x265-SiQ_05352.png
The.Leftovers.S02E05.BluRay.1080p.Dts.H265-d3g_48240.png
The.Resort.S01E03.Tempus.Exhaurire.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_11112.png
The.X-Files.S01E01.Pilot.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_08664.png
The.X-Files.S01E23.Roland.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_50880.png
The.X-Files.S03E21.Avatar.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_47544.png
The.X-Files.S10E01.My.Struggle.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_11904.png
White.Collar.S02E05.1080p.WEBRip.x265-RARBG_56616.png
White.Collar.S02E09.1080p.WEBRip.x265-RARBG_10080.png
White.Collar.S02E11.1080p.WEBRip.x265-RARBG_24912.png
White.Collar.S04E01.1080p.WEBRip.x265-RARBG_14712.png
White.Collar.S05E01.1080p.WEBRip.x265-RARBG_26328.png
White.Collar.S05E08.1080p.WEBRip.x265-RARBG_51312.png
Will.&.Grace.S02E06.To.Serve.and.Disinfect.480p.Web.h264-JBee_34344.png
Will.&.Grace.S03E10.Threes.a.Crowd.Six.Is.a.Freak.Show.480p.Web.h264-JBee_07032.png
Will.&.Grace.S03E15.My.Uncle.the.Car.480p.Web.h264-JBee_30672.png
Will.&.Grace.S04E11.Stakin.Care.of.Business.480p.Web.h264-JBee_13608.png
Will.&.Grace.S04E12.Jingle.Balls.480p.Web.h264-JBee_12168.png
Will.&.Grace.S04E25.A.Buncha.White.Chicks.Sittin.Around.Talkin.480p.Web.h264-JBee_05208.png
Will.&.Grace.S06E13.Ice.Cream.Balls.480p.Web.h264-JBee_00768.png
Will.&.Grace.S06E19.No.Sex.n.the.City.480p.Web.h264-JBee_24120.png
Will.&.Grace.S06E24.Oh.No.You.Di-int.Part.2.480p.Web.h264-JBee_12888.png
Will.&.Grace.S07E20.The.Blonde.Leading.the.Blind.1080p.Web.h264-JBee_02592.png
Will.&.Grace.S08E20.The.Mourning.Son.1080p.Web.h264-JBee_12936.png
Will.&.Grace.S09E04.Grandpa.Jack.1080p.Web.h264-JBee_21672.png
Will.&.Grace.S09E04.Grandpa.Jack.1080p.Web.h264-JBee_25536.png
Will.&.Grace.S09E11.Staten.Island.Fairy.1080p.Web.h264-JBee_21144.png
Will.&.Grace.S10E07.So.Long.Division.1080p.Web.h264-JBee_07344.png
Will.&.Grace.S10E16.Conscious.Coupling.1080p.Web.h264-JBee_21384.png
Will.&.Grace.S11E06.Performance.Anxiety.1080p.Web.h264-JBee_18432.png
Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web.h264-JBee_00168.png
Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web.h264-JBee_30048.png

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

### BatchFace

In [37]:
batch_status = compare_faces(batchface_df, faces)
show_heatmap(batch_status)

In [27]:
batch_status[batch_status['status']=='fp'][['name', 'face_num', 'confidence']]

                                                   name  face_num  confidence
4     Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png         2    0.960874
8     Billions.S02E07.1080p.BluRay.x265-RARBG_39816.png         1    0.526186
17    Billions.S04E05.1080p.WEBRip.x265-RARBG_37200.png         1    0.820354
28    Billions.S05E08.1080p.WEBRip.x265-RARBG_72000.png         1    0.569218
40    Carnivale.S01E10.1080p.WEBRip.10Bit.EAC3.H265-...         1    0.653868
...                                                 ...       ...         ...
2459  Will.&.Grace.S11E06.Performance.Anxiety.1080p....        14    0.589030
2462  Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....         2    0.995879
2463  Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....         3    0.591159
2467  Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....         3    0.911256
2468  Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....         4    0.722230

[616 rows x 3 columns]

In [25]:
temp = batch_status[batch_status['status']=='fp']['name'].unique().tolist()
print(len(temp))
[print(x) for x in temp]

349
Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
Billions.S02E07.1080p.BluRay.x265-RARBG_39816.png
Billions.S04E05.1080p.WEBRip.x265-RARBG_37200.png
Billions.S05E08.1080p.WEBRip.x265-RARBG_72000.png
Carnivale.S01E10.1080p.WEBRip.10Bit.EAC3.H265-d3g_11904.png
Carnivale.S02E03.1080p.WEBRip.10Bit.EAC3.H265-d3g_35616.png
Carnivale.S02E04.1080p.WEBRip.10Bit.EAC3.H265-d3g_32664.png
Carnivale.S02E09.1080p.WEBRip.10Bit.EAC3.H265-d3g_60816.png
Cheers.S01E02.1080p.BluRay.x265-RARBG_11184.png
Cheers.S01E09.1080p.BluRay.x265-RARBG_29496.png
Cheers.S01E22.1080p.BluRay.x265-RARBG_25800.png
Cheers.S02E06.1080p.BluRay.x265-RARBG_24360.png
Cheers.S02E20.1080p.BluRay.x265-RARBG_15768.png
Cheers.S03E01.1080p.BluRay.x265-RARBG_32352.png
Cheers.S03E05.1080p.BluRay.x265-RARBG_33960.png
Cheers.S03E05.1080p.BluRay.x265-RARBG_34080.png
Cheers.S03E06.1080p.BluRay.x265-RARBG_31200.png
Cheers.S03E07.1080p.BluRay.x265-RARBG_16704.png
Cheers.S03E07.1080p.BluRay.x265-RARBG_25800.png
Cheers.S03E18.1080p.BluRay.x265-RARBG_31848.png
Cheers.S03E25.1080p.BluRay.x265-RARBG_13920.png
Cheers.S04E09.1080p.BluRay.x265-RARBG_31872.png
Cheers.S04E15.1080p.BluRay.x265-RARBG_01104.png
Cheers.S04E23.1080p.BluRay.x265-RARBG_14064.png
Cheers.S05E13.1080p.BluRay.x265-RARBG_22224.png
Cheers.S05E15.1080p.BluRay.x265-RARBG_29352.png
Cheers.S05E19.1080p.BluRay.x265-RARBG_13200.png
Cheers.S05E21.1080p.BluRay.x265-RARBG_06696.png
Cheers.S05E26.1080p.BluRay.x265-RARBG_11064.png
Cheers.S06E02.1080p.BluRay.x265-RARBG_18792.png
Cheers.S06E02.1080p.BluRay.x265-RARBG_32280.png
Cheers.S06E05.1080p.BluRay.x265-RARBG_19800.png
Cheers.S06E08.1080p.BluRay.x265-RARBG_00120.png
Cheers.S06E09.1080p.BluRay.x265-RARBG_26112.png
Cheers.S06E22.1080p.BluRay.x265-RARBG_30504.png
Cheers.S07E06.1080p.BluRay.x265-RARBG_06096.png
Cheers.S07E08.1080p.BluRay.x265-RARBG_06768.png
Cheers.S07E14.1080p.BluRay.x265-RARBG_07152.png
Cheers.S07E17.1080p.BluRay.x265-RARBG_23184.png
Cheers.S08E19.1080p.BluRay.x265-RARBG_03720.png
Cheers.S08E19.1080p.BluRay.x265-RARBG_28848.png
Cheers.S08E20.1080p.BluRay.x265-RARBG_26112.png
Cheers.S08E21.1080p.BluRay.x265-RARBG_22464.png
Cheers.S08E21.1080p.BluRay.x265-RARBG_31008.png
Cheers.S09E06.1080p.BluRay.x265-RARBG_23304.png
Cheers.S09E07.1080p.BluRay.x265-RARBG_24432.png
Cheers.S09E09.1080p.BluRay.x265-RARBG_17640.png
Cheers.S09E13.1080p.BluRay.x265-RARBG_16728.png
Cheers.S09E23.1080p.BluRay.x265-RARBG_06960.png
Cheers.S10E03.1080p.BluRay.x265-RARBG_10176.png
Cheers.S10E21.1080p.BluRay.x265-RARBG_20352.png
Cheers.S10E22.1080p.BluRay.x265-RARBG_19992.png
Cheers.S11E08.1080p.BluRay.x265-RARBG_10344.png
Cheers.S11E19.1080p.BluRay.x265-RARBG_00840.png
fargo.s05e02.2160p.web.h265-successfulcrab-sample_0336.png
fargo.s05e04.2160p.web.h265-successfulcrab_51600.png
Fargo.S05E05.The.Tiger.2160p.HULU.WEB-DL.DDP5.1.H.265-NTb_27864.png
fargo.s05e06.2160p.web.h265-successfulcrab-sample_0720.png
For.All.Mankind.S01E01.1080p.WEBRip.x265-RARBG_21456.png
Frasier.S01E02.Space.Quest.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_15360.png
Frasier.S01E04.I.Hate.Frasier.Crane.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_11136.png
Frasier.S01E12.Miracle.on.Third.or.Fourth.Street.1080p.BluRay10Bit.Dts-HDMa2.0.HEVC-d3g_07200.png
Frasier.S02E04.Flour.Child.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_21408.png
Frasier.S02E06.The.Botched.Language.of.the.Cranes.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_17832.png
Frasier.S02E16.The.Show.Where.Sam.Shows.Up.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_22416.png
Frasier.S02E20.Breaking.the.Ice.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_19752.png
Frasier.S02E23.The.Innkeepers.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_05376.png
Frasier.S03E09.Frasier.Grinch.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_22608.png
Frasier.S03E18.Chess.Pains.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_05472.png
Frasier.S03E21.Where.Theres.Smoke.Theres.Fired.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_25488.png
Frasier.S04E05.Head.Game.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_02184.png
Frasier.S04E22.Are.You.Being.Served.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_07320.png
Frasier.S05E16.Beware.of.Greeks.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_11448.png
Frasier.S06E13.The.Show.Where.Woody.Shows.Up.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_29592.png
Frasier.S06E17.Dinner.Party.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_03768.png
Frasier.S07E11.The.Fight.Before.Christmas.2.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_01968.png
Frasier.S08E16.Docu.Drama.1080p.BluRay10Bit.Dts-HDMa2.0.HEVC-d3g_07488.png
Frasier.S09E14.Juvenilia.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_14016.png
Frasier.S09E22.Frasier.Has.Spokane.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_23184.png
Frasier.S10E08.Rooms.with.a.View.2.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_26832.png
Frasier.S10E13.Lilith.Needs.a.Favor.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_21936.png
Frasier.S10E19.Some.Assembly.Required.1080p.BluRay10Bit.Dts-HDMa2.0.HEVC-d3g_06984.png
Frasier.S11E08.Murder.Most.Maris.2.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_13320.png
Frasier.S11E10.Seabee.Jeebies.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_27816.png
Frasier.S11E11.High.Holidays.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_32160.png
Frasier.S11E12.Frasier.Lite.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_29472.png
Frasier.S11E14.Freudian.Sleep.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_27792.png
Frasier.S11E23-E24.Goodnight.Seattle.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_25968.png
Fringe.S01E05.Power.Hungry.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_46824.png
Fringe.S01E13.The.Transformation.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_50376.png
Fringe.S01E20.There's.More.Than.One.of.Everything.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_14640.png
Fringe.S02E02.Night.of.Desirable.Objects.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_30216.png
Fringe.S02E05.Dream.Logic.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_10488.png
Fringe.S02E05.Dream.Logic.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_16008.png
Fringe.S02E06.Earthling.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_42336.png
Fringe.S02E11.Unearthed.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_02472.png
Fringe.S02E14.The.Bishop.Revival.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_61080.png
Fringe.S02E20.Brown.Betty.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_52584.png
Fringe.S03E02.The.Box.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_56880.png
Fringe.S03E17.Stowaway.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_32280.png
Fringe.S04E01.Neither.Here.Nor.There.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_33072.png
Fringe.S04E17.Everything.in.Its.Right.Place.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_49056.png
From.S01E06.Book.74.2160p.WEB-DL.DDP5.1.HEVC-TEPES_50496.png
From.S01E09.Into.the.Woods.2160p.WEB-DL.DDP5.1.HEVC-TEPES_08280.png
Legion.S01E03.1080p.BluRay.x265-RARBG_20856.png
Lost.Girl.S01E03.Oh.Kappa.My.Kappa.BluRay.10Bit.1080p.DD5.1.H265-d3g_39336.png
Lost.Girl.S01E12.Dis.Members.Only.BluRay.10Bit.1080p.DD5.1.H265-d3g_39744.png
Lost.Girl.S02E01.Something.Wicked.This.Fae.Comes.BluRay.10Bit.1080p.DD5.1.H265-d3g_32544.png
Lost.Girl.S02E05.BrotherFae.of.the.Wolves.BluRay.10Bit.1080p.DD5.1.H265-d3g_27072.png
Lost.Girl.S02E06.Its.Better.to.Burn.Out.Than.Fae.Away.BluRay.10Bit.1080p.DD5.1.H265-d3g_58368.png
Lost.Girl.S02E07.Fae.Gone.Wild.BluRay.10Bit.1080p.DD5.1.H265-d3g_54264.png
Lost.Girl.S02E16.Schools.Out.BluRay.10Bit.1080p.DD5.1.H265-d3g_35400.png
Lost.Girl.S03E07.Theres.Bo.Place.Like.Home.BluRay.10Bit.1080p.DD5.1.H265-d3g_45936.png
Lost.Girl.S03E11.Adventures.in.Fae-bysitting.BluRay.10Bit.1080p.DD5.1.H265-d3g_16776.png
Lost.Girl.S03E11.Adventures.in.Fae-bysitting.BluRay.10Bit.1080p.DD5.1.H265-d3g_56232.png
Lost.Girl.S03E13.Those.Who.Wander.BluRay.10Bit.1080p.DD5.1.H265-d3g_54360.png
Lost.Girl.S04E01.In.Memoriam.BluRay.10Bit.1080p.DD5.1.H265-d3g_40080.png
Lost.Girl.S04E08.Groundhog.Fae.BluRay.10Bit.1080p.DD5.1.H265-d3g_55416.png
Lost.Girl.S04E11.End.of.a.Line.BluRay.10Bit.1080p.DD5.1.H265-d3g_36984.png
Lost.Girl.S04E13.Dark.Horse.BluRay.10Bit.1080p.DD5.1.H265-d3g_08352.png
Lost.Girl.S05E04.When.God.Opens.a.Window.BluRay.10Bit.1080p.DD5.1.H265-d3g_02424.png
Lost.Girl.S05E05.Its.Your.Lucky.Fae.BluRay.10Bit.1080p.DD5.1.H265-d3g_46776.png
Modern.Family.S01E03.1080p.BluRay.x265-RARBG_18960.png
Lost.Girl.S05E14.Follow.the.Yellow.Trick.Road.BluRay.10Bit.1080p.DD5.1.H265-d3g_33024.png
Lost.Girl.S05E14.Follow.the.Yellow.Trick.Road.BluRay.10Bit.1080p.DD5.1.H265-d3g_62184.png
Lost.Girl.S05E15.Let.Them.Burn.BluRay.10Bit.1080p.DD5.1.H265-d3g_22056.png
Modern.Family.S01E23.1080p.BluRay.x265-RARBG_10200.png
Modern.Family.S02E10.1080p.BluRay.x265-RARBG_19200.png
Modern.Family.S02E13.1080p.BluRay.x265-RARBG_19584.png
Modern.Family.S02E13.1080p.BluRay.x265-RARBG_28992.png
Modern.Family.S02E16.1080p.BluRay.x265-RARBG_25152.png
Modern.Family.S02E23.1080p.BluRay.x265-RARBG_08304.png
Modern.Family.S03E06.1080p.BluRay.x265-RARBG_21504.png
Modern.Family.S03E08.1080p.BluRay.x265-RARBG_23784.png
Modern.Family.S03E09.1080p.BluRay.x265-RARBG_04248.png
Modern.Family.S03E11.1080p.BluRay.x265-RARBG_15072.png
Modern.Family.S03E23.1080p.BluRay.x265-RARBG_18888.png
Modern.Family.S04E14.1080p.BluRay.x265-RARBG_04152.png
Modern.Family.S05E04.Farm.Strong.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_06816.png
Modern.Family.S05E05.The.Late.Show.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_28104.png
Modern.Family.S05E13.Three.Dinners.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_03960.png
Modern.Family.S05E13.Three.Dinners.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_15480.png
Modern.Family.S06E12.The.Big.Guns.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_02976.png
Modern.Family.S06E17.Closet.Youll.Love.It.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_26688.png
Modern.Family.S06E18.Spring.Break.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_08064.png
Modern.Family.S06E19.Grill.Interrupted.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_12000.png
Modern.Family.S07E04.She.Crazy.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_18432.png
Modern.Family.S07E08.Clean.Out.Your.Junk.Drawer.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_16104.png
Modern.Family.S07E13.Thunk.in.the.Trunk.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_16128.png
Modern.Family.S07E15.I.Dont.Know.How.She.Does.It.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_06144.png
Modern.Family.S08E05.Halloween.4.The.Revenge.of.Rod.Skyhook.1080p.DSNP.WEB-DL.DDP5.1.H.264-FAMiLY_21312.png
Modern.Family.S08E18.Five.Minutes.1080p.DSNP.WEB-DL.DDP5.1.H.264-FAMiLY_05160.png
Modern.Family.S08E20.All.Things.Being.Equal.1080p.DSNP.WEB-DL.DDP5.1.H.264-FAMiLY_18048.png
Modern.Family.S09E22.Clash.of.Swords.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_16632.png
Modern.Family.S10E04.Torn.Between.Two.Lovers.1080p.DSNP.WEB-DL.DDP5.1.H.264-OLDFAMiLY_11904.png
Modern.Family.S10E05.Good.Grief.1080p.DSNP.WEB-DL.DDP5.1.H.264-OLDFAMiLY_23376.png
Modern.Family.S10E11.A.Moving.Day.1080p.DSNP.WEB-DL.DDP5.1.H.264-OLDFAMiLY_27360.png
Modern.Family.S11E09.The.Last.Christmas.1080p.DSNP.WEB-DL.DDP5.1.H.264-WKS_10008.png
Modern.Family.S11E09.The.Last.Christmas.1080p.DSNP.WEB-DL.DDP5.1.H.264-WKS_26784.png
Modern.Family.S11E12.Dead.on.a.Rival.1080p.DSNP.WEB-DL.DDP5.1.H.264-ZigZag_18888.png
Party Down (2009) - S01E02 - California College Conservative Union Caucus (1080p AMZN WEBRip x265 Panda)_15720.png
Party Down (2009) - S01E05 - Sin Say Shun Awards Afterparty (1080p AMZN WEBRip x265 Panda)_22704.png
Russian.Doll.S01E02.2160p.HDR.NF.WEBRip.DDP5.1.x265-TrollUHD_21696.png
Russian.Doll.S01E03.2160p.HDR.NF.WEBRip.DDP5.1.x265-TrollUHD_08352.png
Russian.Doll.S01E08.2160p.HDR.NF.WEBRip.DDP5.1.x265-TrollUHD_00936.png
Scrubs S01E07 My Super Ego  [1080p x265 10bit Joy]_07752.png
Scrubs S01E07 My Super Ego  [1080p x265 10bit Joy]_18504.png
Scrubs S01E09 My Day Off  [1080p x265 10bit Joy]_23352.png
Scrubs S02E08 My Fruit Cups  [1080p x265 10bit Joy]_30936.png
Scrubs S02E12 My New Old Friend  [1080p x265 10bit Joy]_29664.png
Scrubs S02E18 My T.C.W. (c)  [1080p x265 10bit Joy]_20880.png
Scrubs S03E06 My Advice to You  [1080p x265 10bit Joy]_22920.png
Scrubs S03E10 My Rule of Thumb  [1080p x265 10bit Joy]_10128.png
Scrubs S03E14 My Screw Up  [1080p x265 10bit Joy]_05952.png
Scrubs S04E10 My Female Trouble  [1080p x265 10bit Joy]_11712.png
Scrubs S04E11 My Unicorn  [1080p x265 10bit Joy]_09264.png
Scrubs S04E17 My Life In Four Cameras (c)  [1080p x265 10bit Joy]_28080.png
Scrubs S04E23 My Faith In Humanity  [1080p x265 10bit Joy]_03456.png
Scrubs S04E25 My Changing Ways  [1080p x265 10bit Joy]_08112.png
Scrubs S05E04 My Jiggly Ball  [1080p x265 10bit Joy]_02520.png
Scrubs S05E04 My Jiggly Ball  [1080p x265 10bit Joy]_11880.png
Scrubs S05E08 My Big Bird (c)  [1080p x265 10bit Joy]_20016.png
Scrubs S05E15 My Extra Mile  [1080p x265 10bit Joy]_03768.png
Scrubs S05E16 My Bright Idea  [1080p x265 10bit Joy]_15432.png
Scrubs S05E23 My Urologist  [1080p x265 10bit Joy]_32952.png
Scrubs S06E03 My Coffee  [1080p x265 10bit Joy]_22536.png
Scrubs S06E20 My Conventional Wisdom  [1080p x265 10bit Joy]_22704.png
Scrubs S06E20 My Conventional Wisdom  [1080p x265 10bit Joy]_39912.png
Scrubs S07E03 My Inconvenient Truth  [1080p x265 10bit Joy]_03096.png
Scrubs S07E05 My Growing Pains  [1080p x265 10bit Joy]_06936.png
Scrubs S07E05 My Growing Pains  [1080p x265 10bit Joy]_25608.png
Scrubs S07E11 My Princess  [1080p x265 10bit Joy]_11208.png
Scrubs S08E06 My Cookie Pants  [1080p x265 10bit Joy]_12792.png
Scrubs S08E11 My Nah Nah Nah  [1080p x265 10bit Joy]_12792.png
Scrubs S08E14 My Soul on Fire Part 1  [1080p x265 10bit Joy]_16560.png
Scrubs S08E19 My Finale Part 2  [1080p x265 10bit Joy]_20088.png
Scrubs S08E19 My Finale Part 2  [1080p x265 10bit Joy]_27144.png
Scrubs S09E02 Our Drunk Friend  [1080p x265 10bit Joy]_15024.png
Scrubs S09E05 Our Mysteries  [1080p x265 10bit Joy]_03432.png
Scrubs S09E05 Our Mysteries  [1080p x265 10bit Joy]_24360.png
Scrubs S09E13 Our Thanks  [1080p x265 10bit Joy]_02520.png
Seinfeld.S01E01.1080p.WEBRip.x265-RARBG_07608.png
Seinfeld.S01E01.1080p.WEBRip.x265-RARBG_27912.png
Seinfeld.S02E01.1080p.WEBRip.x265-RARBG_06888.png
Seinfeld.S02E09.1080p.WEBRip.x265-RARBG_03648.png
Seinfeld.S02E11.1080p.WEBRip.x265-RARBG_28440.png
Seinfeld.S02E12.1080p.WEBRip.x265-RARBG_27408.png
Seinfeld.S03E02.1080p.WEBRip.x265-RARBG_23880.png
Seinfeld.S03E10.1080p.WEBRip.x265-RARBG_31464.png
Seinfeld.S03E16.1080p.WEBRip.x265-RARBG_03048.png
Seinfeld.S03E17.1080p.WEBRip.x265-RARBG_14712.png
Seinfeld.S04E08.1080p.WEBRip.x265-RARBG_09048.png
Seinfeld.S04E08.1080p.WEBRip.x265-RARBG_26784.png
Seinfeld.S04E17.1080p.WEBRip.x265-RARBG_27144.png
Seinfeld.S04E18.1080p.WEBRip.x265-RARBG_27072.png
Seinfeld.S05E01.1080p.WEBRip.x265-RARBG_16680.png
Seinfeld.S05E03.1080p.WEBRip.x265-RARBG_04056.png
Seinfeld.S05E13.1080p.WEBRip.x265-RARBG_25896.png
Seinfeld.S05E16.1080p.WEBRip.x265-RARBG_28464.png
Seinfeld.S05E17.1080p.WEBRip.x265-RARBG_15216.png
Seinfeld.S06E09.1080p.WEBRip.x265-RARBG_27768.png
Seinfeld.S07E06.1080p.WEBRip.x265-RARBG_23184.png
Seinfeld.S07E16.1080p.WEBRip.x265-RARBG_16896.png
Seinfeld.S08E06.1080p.WEBRip.x265-RARBG_17328.png
Seinfeld.S08E12.1080p.WEBRip.x265-RARBG_14256.png
Seinfeld.S08E15.1080p.WEBRip.x265-RARBG_31272.png
Seinfeld.S08E21.1080p.WEBRip.x265-RARBG_16272.png
Seinfeld.S09E09.1080p.WEBRip.x265-RARBG_11160.png
Seinfeld.S09E11.1080p.WEBRip.x265-RARBG_02856.png
Seinfeld.S09E12.1080p.WEBRip.x265-RARBG_29304.png
Seinfeld.S09E13.1080p.WEBRip.x265-RARBG_15624.png
Seinfeld.S09E21.1080p.WEBRip.x265-RARBG_47736.png
Seinfeld.S09E22.1080p.WEBRip.x265-RARBG_02568.png
Servant.S03E02.Hive.2160p.ATVP.WEB-DL.DDP5.1.HDR.HEVC-CasStudio_19608.png
Servant.S03E02.Hive.2160p.ATVP.WEB-DL.DDP5.1.HDR.HEVC-CasStudio_31728.png
Servant.S03E07.Camp.2160p.ATVP.WEB-DL.DDP5.1.HDR.HEVC-CasStudio_35232.png
Servant.S03E09.Commitment.2160p.ATVP.WEB-DL.DDP5.1.HDR.HEVC-CasStudio_36528.png
Silo.S01E07.The.Flamekeepers.2160p.ATVP.WEB-DL.DDP5.1.HDR.H.265-NTb_20496.png
Suits.S01E01.1080p.BluRay.x265-RARBG_048528.png
Suits.S01E03.1080p.BluRay.x265-RARBG_09816.png
Suits.S02E01.1080p.BluRay.x265-RARBG_58704.png
Suits.S02E11.1080p.BluRay.x265-RARBG_10416.png
Suits.S04E02.1080p.BluRay.x265-RARBG_34104.png
Suits.S04E05.1080p.BluRay.x265-RARBG_25896.png
Suits.S04E09.1080p.BluRay.x265-RARBG_11640.png
Suits.S05E11.1080p.BluRay.x265-RARBG_39696.png
Suits.S06E04.1080p.BluRay.x265-RARBG_41952.png
Suits.S06E15.1080p.BluRay.x265-RARBG_42504.png
Suits.S07E06.1080p.BluRay.x265-RARBG_10584.png
Suits.S08E02.1080p.BluRay.x265-RARBG_01656.png
Suits.S08E08.1080p.BluRay.x265-RARBG_25512.png
Ted.Lasso.S02E04.Carol.of.the.Bells.AAC.5.1.1080p.WEBRip.x265-SiQ_05352.png
Ted.Lasso.S02E07.Headspace.AAC.5.1.1080p.WEBRip.x265-SiQ_30768.png
The.Leftovers.S02E01.BluRay.1080p.Dts.H265-d3g_40968.png
The.Leftovers.S02E05.BluRay.1080p.Dts.H265-d3g_48240.png
The.Leftovers.S02E07.BluRay.1080p.Dts.H265-d3g_17544.png
The.Leftovers.S03E08.BluRay.1080p.Dts.H265-d3g_092856.png
The.Leftovers.S03E08.BluRay.1080p.Dts.H265-d3g_098736.png
The.Prisoner.1967.S01E07.Many.Happy.Returns.1080p.BluRay.x264-CiNEFiLE_22152.png
The.Resort.S01E03.Tempus.Exhaurire.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_11112.png
The.Resort.S01E04.The.History.of.Forgetting.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_29448.png
The.Resort.S01E05.El.Espejo.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_04680.png
The.Resort.S01E08.The.Disillusionment.of.Time.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_27672.png
The.X-Files.S01E01.Pilot.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_08664.png
The.X-Files.S01E05.The.Jersey.Devil.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_57816.png
The.X-Files.S01E09.Space.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_29160.png
The.X-Files.S01E10.Fallen.Angel.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_46728.png
The.X-Files.S01E11.Eve.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_65016.png
The.X-Files.S01E17.E.B.E..1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_54000.png
The.X-Files.S02E06.Ascension.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_50280.png
The.X-Files.S02E11.Excelsis.Dei.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_10560.png
The.X-Files.S02E14.Die.Hand.Die.Verletzt.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_34464.png
The.X-Files.S02E15.Fresh.Bones.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_06048.png
The.X-Files.S02E15.Fresh.Bones.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_10080.png
The.X-Files.S02E16.Colony.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_16200.png
The.X-Files.S02E18.Fearful.Symmetry.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_01992.png
The.X-Files.S02E25.Anasazi.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_01440.png
The.X-Files.S03E04.Clyde.Bruckmans.Final.Repose.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_42840.png
The.X-Files.S03E12.War.of.the.Coprophages.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_52032.png
The.X-Files.S03E16.Apocrypha.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_04728.png
The.X-Files.S03E16.Apocrypha.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_04968.png
The.X-Files.S03E21.Avatar.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_47544.png
The.X-Files.S04E03.Teliko.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_38256.png
The.X-Files.S04E12.Leonard.Betts.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_28848.png
The.X-Files.S04E19.Synchrony.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_24624.png
The.X-Files.S04E22.Elegy.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_59568.png
The.X-Files.S05E19.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_37128.png
The.X-Files.S06E05.Dreamland.II.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_47736.png
The.X-Files.S06E22.Biogenesis.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_27648.png
The.X-Files.S07E04.Millennium.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_29400.png
The.X-Files.S08E02.Without.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_60432.png
The.X-Files.S08E11.The.Gift.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_52080.png
The.X-Files.S08E11.The.Gift.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_54312.png
The.X-Files.S09E03.Daemonicus.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_01008.png
The.X-Files.S09E04.4-D.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_12048.png
The.X-Files.S09E05.Lord.of.the.Flies.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_03696.png
The.X-Files.S09E08.Hellbound.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_42984.png
The.X-Files.S09E17.Release.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_58848.png

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

### RetinaCustom

In [30]:
custom_status = compare_faces(custom_df, faces)
show_heatmap(custom_status)

### MTCNN

In [119]:
torch_status = compare_faces(torch_df, faces)
show_heatmap(torch_status)

### OpenCV

In [120]:
cv_status = compare_faces(cv_df, faces)
show_heatmap(cv_status)

## Validation

In [28]:
temp = faces.merge(dlib_df,
                     on=['name', 'face_num'],
                     how='left')
temp

,name,img_height_x,img_width_x,x1_x,y1_x,x2_x,y2_x,width_x,height_x,area_x,...,y1_y,x2_y,y2_y,width_y,height_y,area_y,confidence,img_width_y,img_height_y,pct_of_frame_y
0,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png,1080,1920,323,5,919,731,596,726,432696,...,251.0,938.0,659.0,408.0,408.0,166464.0,1.156534,1920.0,1080.0,0.080278
1,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png,1080,1920,262,42,614,507,352,465,163680,...,181.0,522.0,464.0,283.0,283.0,80089.0,1.043341,1920.0,1080.0,0.038623
2,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,484,389,671,617,187,228,42636,...,450.0,683.0,586.0,137.0,136.0,18632.0,0.667519,1920.0,1080.0,0.008985
3,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,1003,42,1195,261,192,219,42048,...,109.0,1110.0,223.0,114.0,114.0,12996.0,0.637119,1920.0,1080.0,0.006267
4,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png,1080,1920,1121,66,1662,824,541,758,410078,...,296.0,1534.0,785.0,489.0,489.0,239121.0,1.075798,1920.0,1080.0,0.115317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....,1080,1920,1612,261,1704,361,92,100,9200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1891,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...,1080,1920,457,103,579,237,122,134,16348,...,228.0,859.0,307.0,79.0,79.0,6241.0,1.052727,1920.0,1080.0,0.003010
1892,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...,1080,1920,778,223,868,330,90,107,9630,...,127.0,579.0,222.0,94.0,95.0,8930.0,1.017996,1920.0,1080.0,0.004307
1893,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...,1080,1920,1240,204,1313,331,73,127,9271,...,228.0,1307.0,307.0,79.0,79.0,6241.0,0.669482,1920.0,1080.0,0.003010
1894,Will.&.Grace.S11E17.New.Crib.1080p.Web.h264-JB...,1080,1920,990,139,1254,424,264,285,75240,...,181.0,1208.0,417.0,236.0,236.0,55696.0,1.066103,1920.0,1080.0,0.026860

In [29]:
dlib_df.shape

(1203, 13)

In [30]:
faces

,name,img_height,img_width,x1,y1,x2,y2,width,height,area,pct_of_frame,face_num
0,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png,1080,1920,323,5,919,731,596,726,432696,0.208669,0
1,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png,1080,1920,262,42,614,507,352,465,163680,0.078935,0
2,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,484,389,671,617,187,228,42636,0.020561,0
3,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,1003,42,1195,261,192,219,42048,0.020278,1
4,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png,1080,1920,1121,66,1662,824,541,758,410078,0.197761,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1890,Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....,1080,1920,1612,261,1704,361,92,100,9200,0.004437,2
1891,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...,1080,1920,457,103,579,237,122,134,16348,0.007884,0
1892,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...,1080,1920,778,223,868,330,90,107,9630,0.004644,1
1893,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...,1080,1920,1240,204,1313,331,73,127,9271,0.004471,2
1894,Will.&.Grace.S11E17.New.Crib.1080p.Web.h264-JB...,1080,1920,990,139,1254,424,264,285,75240,0.036285,0

In [31]:
dlib_df[dlib_df.duplicated(subset=['name', 'face_num'], keep=False)]

Empty DataFrame
Columns: [x1, y1, x2, y2, width, height, area, confidence, face_num, img_width, img_height, pct_of_frame, name]
Index: []

In [32]:
temp = dlib_df.merge(faces,
                     on=['name', 'face_num'],
                     how='left')
temp.head()

,x1_x,y1_x,x2_x,y2_x,width_x,height_x,area_x,confidence,face_num,img_width_x,...,img_height_y,img_width_y,x1_y,y1_y,x2_y,y2_y,width_y,height_y,area_y,pct_of_frame_y
0,530,251,938,659,408,408,166464,1.156534,0,1920,...,1080.0,1920.0,323.0,5.0,919.0,731.0,596.0,726.0,432696.0,0.208669
1,239,181,522,464,283,283,80089,1.043341,0,1920,...,1080.0,1920.0,262.0,42.0,614.0,507.0,352.0,465.0,163680.0,0.078935
2,546,450,683,586,137,136,18632,0.667519,0,1920,...,1080.0,1920.0,484.0,389.0,671.0,617.0,187.0,228.0,42636.0,0.020561
3,996,109,1110,223,114,114,12996,0.637119,1,1920,...,1080.0,1920.0,1003.0,42.0,1195.0,261.0,192.0,219.0,42048.0,0.020278
4,1045,296,1534,785,489,489,239121,1.075798,0,1920,...,1080.0,1920.0,1121.0,66.0,1662.0,824.0,541.0,758.0,410078.0,0.197761

In [33]:
fp = temp[temp['x1_y'].isna()]
fp.shape

(6, 23)

In [34]:
temp.shape

(1203, 23)

In [35]:
eph = faces.merge(dlib_df,
            on=['name', 'face_num'],
            how='left')
eph[eph['x1_y'].isna()].shape

(698, 23)

In [36]:
eph[eph['x1_y'].isna()]

,name,img_height_x,img_width_x,x1_x,y1_x,x2_x,y2_x,width_x,height_x,area_x,...,y1_y,x2_y,y2_y,width_y,height_y,area_y,confidence,img_width_y,img_height_y,pct_of_frame_y
10,Billions.S04E02.1080p.WEBRip.x265-RARBG_52416.png,1080,1920,535,160,801,465,266,305,81130,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Billions.S04E10.1080p.WEBRip.x265-RARBG_15288.png,1080,1920,1037,245,1238,483,201,238,47838,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Billions.S04E10.1080p.WEBRip.x265-RARBG_15288.png,1080,1920,1500,383,1801,709,301,326,98126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Billions.S06E08.1080p.WEBRip.x265-RARBG_27264.png,1080,1920,1130,119,1311,343,181,224,40544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Billions.S06E10.1080p.WEBRip.x265-RARBG_73680.png,1080,1920,87,286,170,406,83,120,9960,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1883,Will.&.Grace.S11E06.Performance.Anxiety.1080p....,1080,1920,1529,213,1596,288,67,75,5025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1884,Will.&.Grace.S11E06.Performance.Anxiety.1080p....,1080,1920,1470,206,1523,280,53,74,3922,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1885,Will.&.Grace.S11E06.Performance.Anxiety.1080p....,1080,1920,1700,188,1763,272,63,84,5292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1887,Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....,1080,1920,1179,235,1307,389,128,154,19712,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1890,Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....,1080,1920,1612,261,1704,361,92,100,9200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
dlib_df

,x1,y1,x2,y2,width,height,area,confidence,face_num,img_width,img_height,pct_of_frame,name
0,530,251,938,659,408,408,166464,1.156534,0,1920,1080,0.080278,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png
1,239,181,522,464,283,283,80089,1.043341,0,1920,1080,0.038623,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png
2,546,450,683,586,137,136,18632,0.667519,0,1920,1080,0.008985,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
3,996,109,1110,223,114,114,12996,0.637119,1,1920,1080,0.006267,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png
4,1045,296,1534,785,489,489,239121,1.075798,0,1920,1080,0.115317,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,1164,164,1243,243,79,79,6241,0.990481,1,1920,1080,0.003010,Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....
1199,780,228,859,307,79,79,6241,1.052727,0,1920,1080,0.003010,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...
1200,485,127,579,222,94,95,8930,1.017996,1,1920,1080,0.004307,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...
1201,1228,228,1307,307,79,79,6241,0.669482,2,1920,1080,0.003010,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...
1202,972,181,1208,417,236,236,55696,1.066103,0,1920,1080,0.026860,Will.&.Grace.S11E17.New.Crib.1080p.Web.h264-JB...

In [38]:
retina_status[retina_status['status'] == 'fp']['name'].unique().tolist()

['Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png',
 'Cheers.S02E06.1080p.BluRay.x265-RARBG_24360.png',
 'Cheers.S03E05.1080p.BluRay.x265-RARBG_33960.png',
 'Cheers.S03E05.1080p.BluRay.x265-RARBG_34080.png',
 'Cheers.S03E06.1080p.BluRay.x265-RARBG_31200.png',
 'Cheers.S03E07.1080p.BluRay.x265-RARBG_16704.png',
 'Cheers.S03E18.1080p.BluRay.x265-RARBG_31848.png',
 'Cheers.S03E25.1080p.BluRay.x265-RARBG_13920.png',
 'Cheers.S04E15.1080p.BluRay.x265-RARBG_01104.png',
 'Cheers.S04E23.1080p.BluRay.x265-RARBG_14064.png',
 'Cheers.S05E21.1080p.BluRay.x265-RARBG_06696.png',
 'Cheers.S06E08.1080p.BluRay.x265-RARBG_00120.png',
 'Cheers.S06E09.1080p.BluRay.x265-RARBG_26112.png',
 'Cheers.S06E20.1080p.BluRay.x265-RARBG_30912.png',
 'Cheers.S06E22.1080p.BluRay.x265-RARBG_30504.png',
 'Cheers.S07E08.1080p.BluRay.x265-RARBG_06768.png',
 'Cheers.S08E19.1080p.BluRay.x265-RARBG_28848.png',
 'Cheers.S09E06.1080p.BluRay.x265-RARBG_23304.png',
 'Cheers.S09E23.1080p.BluRay.x265-RARBG_06960.png',
 'Cheers.S10E19.1080p.BluRay.x265-RARBG_16776.png',
 'Cheers.S11E13.1080p.BluRay.x265-RARBG_24672.png',
 'Frasier.S03E19.Crane.vs.Crane.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_14784.png',
 'Frasier.S04E05.Head.Game.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_02184.png',
 'Frasier.S04E22.Are.You.Being.Served.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_07320.png',
 'Frasier.S05E16.Beware.of.Greeks.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_11448.png',
 'Frasier.S06E05.First.Do.No.Harm.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_03000.png',
 'Frasier.S10E13.Lilith.Needs.a.Favor.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_21936.png',
 'Frasier.S11E08.Murder.Most.Maris.2.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_13320.png',
 'Frasier.S11E10.Seabee.Jeebies.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_27816.png',
 'Legion.S03E06.1080p.WEBRip.x265-RARBG_50808.png',
 'Lost.Girl.S02E16.Schools.Out.BluRay.10Bit.1080p.DD5.1.H265-d3g_35400.png',
 'Lost.Girl.S04E01.In.Memoriam.BluRay.10Bit.1080p.DD5.1.H265-d3g_40080.png',
 'Modern.Family.S02E13.1080p.BluRay.x265-RARBG_19584.png',
 'Modern.Family.S03E06.1080p.BluRay.x265-RARBG_21504.png',
 'Modern.Family.S03E11.1080p.BluRay.x265-RARBG_15072.png',
 'Modern.Family.S05E05.The.Late.Show.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_28104.png',
 'Modern.Family.S05E13.Three.Dinners.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_15480.png',
 'Modern.Family.S05E24.The.Wedding.Part.2.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_28800.png',
 'Modern.Family.S06E12.The.Big.Guns.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_02976.png',
 'Modern.Family.S06E16.Connection.Lost.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_04320.png',
 'Modern.Family.S06E17.Closet.Youll.Love.It.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_26688.png',
 'Modern.Family.S06E19.Grill.Interrupted.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_12000.png',
 'Modern.Family.S07E13.Thunk.in.the.Trunk.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_16128.png',
 'Modern.Family.S07E14.The.Storm.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_22272.png',
 'Modern.Family.S07E15.I.Dont.Know.How.She.Does.It.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_06144.png',
 'Modern.Family.S09E22.Clash.of.Swords.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_16632.png',
 'Modern.Family.S10E04.Torn.Between.Two.Lovers.1080p.DSNP.WEB-DL.DDP5.1.H.264-OLDFAMiLY_11904.png',
 'Party Down (2009) - S01E02 - California College Conservative Union Caucus (1080p AMZN WEBRip x265 Panda)_15720.png',
 'Scrubs S03E14 My Screw Up  [1080p x265 10bit Joy]_05952.png',
 'Scrubs S04E10 My Female Trouble  [1080p x265 10bit Joy]_11712.png',
 'Scrubs S04E17 My Life In Four Cameras (c)  [1080p x265 10bit Joy]_28080.png',
 'Scrubs S05E10 Her Story II  [1080p x265 10bit Joy]_24600.png',
 'Scrubs S05E23 My Urologist  [1080p x265 10bit Joy]_32952.png',
 'Scrubs S06E20 My Conventional Wisdom  [1080p x265 10bit Joy]_22704.png',
 'Scrubs S06E20 My Conventional Wisdom  [1080p x265 10bit Joy]_39912.png',
 'Scrubs S07E03 My Inconvenient Truth  [1080p x265 10bit Joy]_03096.png',
 'Scrubs S07E05 My Growing Pains  [1080p x265 10bit Joy]_06936.png',
 'Scrubs S07E05 My Growing Pains  [1080p x265 10bit Joy]_25608.png',
 'Scrubs S08E19 My Finale Part 2  [1080p x265 10bit Joy]_20088.png',
 'Scrubs S08E19 My Finale Part 2  [1080p x265 10bit Joy]_27144.png',
 'Scrubs S09E05 Our Mysteries  [1080p x265 10bit Joy]_03432.png',
 'Scrubs S09E05 Our Mysteries  [1080p x265 10bit Joy]_24360.png',
 'Seinfeld.S01E01.1080p.WEBRip.x265-RARBG_27912.png',
 'Seinfeld.S03E10.1080p.WEBRip.x265-RARBG_31464.png',
 'Seinfeld.S04E08.1080p.WEBRip.x265-RARBG_09048.png',
 'Seinfeld.S04E12.1080p.WEBRip.x265-RARBG_13560.png',
 'Seinfeld.S05E13.1080p.WEBRip.x265-RARBG_25896.png',
 'Seinfeld.S05E17.1080p.WEBRip.x265-RARBG_12648.png',
 'Seinfeld.S09E12.1080p.WEBRip.x265-RARBG_29304.png',
 'Suits.S05E11.1080p.BluRay.x265-RARBG_39696.png',
 'Suits.S06E15.1080p.BluRay.x265-RARBG_42504.png',
 'Ted.Lasso.S02E04.Carol.of.the.Bells.AAC.5.1.1080p.WEBRip.x265-SiQ_05352.png',
 'The.Leftovers.S02E05.BluRay.1080p.Dts.H265-d3g_48240.png',
 'The.Resort.S01E03.Tempus.Exhaurire.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_11112.png',
 'The.X-Files.S01E01.Pilot.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_08664.png',
 'The.X-Files.S01E23.Roland.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_50880.png',
 'The.X-Files.S03E21.Avatar.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_47544.png',
 'The.X-Files.S10E01.My.Struggle.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_11904.png',
 'White.Collar.S02E05.1080p.WEBRip.x265-RARBG_56616.png',
 'White.Collar.S02E09.1080p.WEBRip.x265-RARBG_10080.png',
 'White.Collar.S02E11.1080p.WEBRip.x265-RARBG_24912.png',
 'White.Collar.S04E01.1080p.WEBRip.x265-RARBG_14712.png',
 'White.Collar.S05E01.1080p.WEBRip.x265-RARBG_26328.png',
 'White.Collar.S05E08.1080p.WEBRip.x265-RARBG_51312.png',
 'Will.&.Grace.S02E06.To.Serve.and.Disinfect.480p.Web.h264-JBee_34344.png',
 'Will.&.Grace.S03E10.Threes.a.Crowd.Six.Is.a.Freak.Show.480p.Web.h264-JBee_07032.png',
 'Will.&.Grace.S03E15.My.Uncle.the.Car.480p.Web.h264-JBee_30672.png',
 'Will.&.Grace.S04E11.Stakin.Care.of.Business.480p.Web.h264-JBee_13608.png',
 'Will.&.Grace.S04E12.Jingle.Balls.480p.Web.h264-JBee_12168.png',
 'Will.&.Grace.S04E25.A.Buncha.White.Chicks.Sittin.Around.Talkin.480p.Web.h264-JBee_05208.png',
 'Will.&.Grace.S06E13.Ice.Cream.Balls.480p.Web.h264-JBee_00768.png',
 'Will.&.Grace.S06E19.No.Sex.n.the.City.480p.Web.h264-JBee_24120.png',
 'Will.&.Grace.S06E24.Oh.No.You.Di-int.Part.2.480p.Web.h264-JBee_12888.png',
 'Will.&.Grace.S07E20.The.Blonde.Leading.the.Blind.1080p.Web.h264-JBee_02592.png',
 'Will.&.Grace.S08E20.The.Mourning.Son.1080p.Web.h264-JBee_12936.png',
 'Will.&.Grace.S09E04.Grandpa.Jack.1080p.Web.h264-JBee_21672.png',
 'Will.&.Grace.S09E04.Grandpa.Jack.1080p.Web.h264-JBee_25536.png',
 'Will.&.Grace.S09E11.Staten.Island.Fairy.1080p.Web.h264-JBee_21144.png',
 'Will.&.Grace.S10E07.So.Long.Division.1080p.Web.h264-JBee_07344.png',
 'Will.&.Grace.S10E16.Conscious.Coupling.1080p.Web.h264-JBee_21384.png',
 'Will.&.Grace.S11E06.Performance.Anxiety.1080p.Web.h264-JBee_18432.png',
 'Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web.h264-JBee_00168.png',
 'Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web.h264-JBee_30048.png']

In [41]:
fp = retina_status[retina_status['status'] == 'fp']

In [87]:
temp = retina_df[retina_df['pct_of_frame'] > 0.01]

In [88]:
retina_status_test = compare_faces(temp, faces)

In [89]:
show_heatmap(retina_status_test)

In [ ]:
def compare_faces(source, 
                  faces):
    temp = faces.rename({'x1': 'x1_ground',
            'y1': 'y1_ground',
            'x2': 'x2_ground',
            'y2': 'y2_ground',
            'width': 'width_ground',
            'height': 'height_ground'}, axis=1)
    temp = temp[['x1_ground',
                    'y1_ground',
                    'x2_ground',
                    'y2_ground',
                    'width_ground',
                    'height_ground',
                    'face_num',
                    'name']]

    df = source.merge(temp,
                on=['name', 'face_num'],
                how='left')
    df['status'] = df.apply(lambda x: 'tp' if pd.notna(x['x1_ground']) else 'fp', axis=1)

    rdf = temp.merge(df.drop(['x1_ground', 'y1_ground', 'x2_ground', 'y2_ground', 'width_ground', 'height_ground'], axis=1),
                 on=['name', 'face_num'],
                 how='left')
    rdf['status'] = rdf.apply(lambda x: 'fn' if pd.isna(x['x1']) else np.nan, axis=1)
    fn = rdf[rdf['x1'].isna()]

    df = pd.concat([df, fn], axis=0)
    
    # df['center_x'] = df.apply(lambda x: x['x1'] + int(x['width']/2), axis=1)
    # df['center_y'] = df.apply(lambda x: x['y1'] + int(x['height']/2), axis=1)
    # df['center_ground_x'] = df.apply(lambda x: x['x1_ground'] + int(x['width_ground']/2), axis=1)
    # df['center_ground_y'] = df.apply(lambda x: x['y1_ground'] + int(x['height_ground']/2), axis=1)
    
    return df

In [106]:
temp = dlib_df.merge(faces,
                       on=['name', 'face_num'],
                       how='left')
temp

,x1_x,y1_x,x2_x,y2_x,width_x,height_x,area_x,confidence,face_num,img_width_x,...,img_height_y,img_width_y,x1_y,y1_y,x2_y,y2_y,width_y,height_y,area_y,pct_of_frame_y
0,530,251,938,659,408,408,166464,1.156534,0,1920,...,1080.0,1920.0,323.0,5.0,919.0,731.0,596.0,726.0,432696.0,0.208669
1,239,181,522,464,283,283,80089,1.043341,0,1920,...,1080.0,1920.0,262.0,42.0,614.0,507.0,352.0,465.0,163680.0,0.078935
2,546,450,683,586,137,136,18632,0.667519,0,1920,...,1080.0,1920.0,484.0,389.0,671.0,617.0,187.0,228.0,42636.0,0.020561
3,996,109,1110,223,114,114,12996,0.637119,1,1920,...,1080.0,1920.0,1003.0,42.0,1195.0,261.0,192.0,219.0,42048.0,0.020278
4,1045,296,1534,785,489,489,239121,1.075798,0,1920,...,1080.0,1920.0,1121.0,66.0,1662.0,824.0,541.0,758.0,410078.0,0.197761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,1164,164,1243,243,79,79,6241,0.990481,1,1920,...,1080.0,1920.0,1165.0,127.0,1268.0,255.0,103.0,128.0,13184.0,0.006358
1199,780,228,859,307,79,79,6241,1.052727,0,1920,...,1080.0,1920.0,457.0,103.0,579.0,237.0,122.0,134.0,16348.0,0.007884
1200,485,127,579,222,94,95,8930,1.017996,1,1920,...,1080.0,1920.0,778.0,223.0,868.0,330.0,90.0,107.0,9630.0,0.004644
1201,1228,228,1307,307,79,79,6241,0.669482,2,1920,...,1080.0,1920.0,1240.0,204.0,1313.0,331.0,73.0,127.0,9271.0,0.004471
1202,972,181,1208,417,236,236,55696,1.066103,0,1920,...,1080.0,1920.0,990.0,139.0,1254.0,424.0,264.0,285.0,75240.0,0.036285

In [108]:
fp = temp[temp['x1_y'].isna()]
print(f'({fp.shape[0]}/{temp.shape[0]}) = {fp.shape[0]/temp.shape[0]}')

(6/1203) = 0.004987531172069825

In [109]:
temp = faces.merge(dlib_df,
                   on=['name', 'face_num'],
                   how='left')

In [110]:
fn = temp[temp['x1_y'].isna()]
print(f'({fn.shape[0]}/{temp.shape[0]}) = {fn.shape[0]/temp.shape[0]}')

(698/1895) = 0.3683377308707124

In [113]:
fn['name'].unique().tolist()

['Billions.S04E02.1080p.WEBRip.x265-RARBG_52416.png',
 'Billions.S04E10.1080p.WEBRip.x265-RARBG_15288.png',
 'Billions.S06E08.1080p.WEBRip.x265-RARBG_27264.png',
 'Billions.S06E10.1080p.WEBRip.x265-RARBG_73680.png',
 'Billions.S06E12.1080p.WEBRip.x265-RARBG_10632.png',
 'Carnivale.S02E03.1080p.WEBRip.10Bit.EAC3.H265-d3g_35616.png',
 'Carnivale.S02E04.1080p.WEBRip.10Bit.EAC3.H265-d3g_20880.png',
 'Carnivale.S02E04.1080p.WEBRip.10Bit.EAC3.H265-d3g_32664.png',
 'Carnivale.S02E11.1080p.WEBRip.10Bit.EAC3.H265-d3g_49632.png',
 'Cheers.S01E02.1080p.BluRay.x265-RARBG_11184.png',
 'Cheers.S01E07.1080p.BluRay.x265-RARBG_09000.png',
 'Cheers.S01E09.1080p.BluRay.x265-RARBG_18408.png',
 'Cheers.S01E09.1080p.BluRay.x265-RARBG_29496.png',
 'Cheers.S01E20.1080p.BluRay.x265-RARBG_24480.png',
 'Cheers.S02E01.1080p.BluRay.x265-RARBG_07056.png',
 'Cheers.S02E01.1080p.BluRay.x265-RARBG_26040.png',
 'Cheers.S02E20.1080p.BluRay.x265-RARBG_15768.png',
 'Cheers.S03E03.1080p.BluRay.x265-RARBG_09624.png',
 'Cheers.S03E03.1080p.BluRay.x265-RARBG_23616.png',
 'Cheers.S03E06.1080p.BluRay.x265-RARBG_31200.png',
 'Cheers.S03E07.1080p.BluRay.x265-RARBG_16704.png',
 'Cheers.S03E07.1080p.BluRay.x265-RARBG_25800.png',
 'Cheers.S03E09.1080p.BluRay.x265-RARBG_19920.png',
 'Cheers.S03E13.1080p.BluRay.x265-RARBG_05880.png',
 'Cheers.S03E25.1080p.BluRay.x265-RARBG_13920.png',
 'Cheers.S04E09.1080p.BluRay.x265-RARBG_31872.png',
 'Cheers.S04E14.1080p.BluRay.x265-RARBG_07608.png',
 'Cheers.S04E23.1080p.BluRay.x265-RARBG_14064.png',
 'Cheers.S05E13.1080p.BluRay.x265-RARBG_19392.png',
 'Cheers.S05E23.1080p.BluRay.x265-RARBG_27864.png',
 'Cheers.S05E26.1080p.BluRay.x265-RARBG_22896.png',
 'Cheers.S06E02.1080p.BluRay.x265-RARBG_18792.png',
 'Cheers.S06E08.1080p.BluRay.x265-RARBG_00120.png',
 'Cheers.S06E09.1080p.BluRay.x265-RARBG_05688.png',
 'Cheers.S06E09.1080p.BluRay.x265-RARBG_26112.png',
 'Cheers.S06E11.1080p.BluRay.x265-RARBG_09408.png',
 'Cheers.S06E14.1080p.BluRay.x265-RARBG_16200.png',
 'Cheers.S06E16.1080p.BluRay.x265-RARBG_04632.png',
 'Cheers.S06E22.1080p.BluRay.x265-RARBG_30504.png',
 'Cheers.S07E04.1080p.BluRay.x265-RARBG_33048.png',
 'Cheers.S07E06.1080p.BluRay.x265-RARBG_06096.png',
 'Cheers.S07E06.1080p.BluRay.x265-RARBG_06360.png',
 'Cheers.S07E08.1080p.BluRay.x265-RARBG_06768.png',
 'Cheers.S07E16.1080p.BluRay.x265-RARBG_14112.png',
 'Cheers.S07E16.1080p.BluRay.x265-RARBG_14280.png',
 'Cheers.S08E16.1080p.BluRay.x265-RARBG_08400.png',
 'Cheers.S08E19.1080p.BluRay.x265-RARBG_28848.png',
 'Cheers.S08E20.1080p.BluRay.x265-RARBG_26112.png',
 'Cheers.S08E21.1080p.BluRay.x265-RARBG_22464.png',
 'Cheers.S08E24.1080p.BluRay.x265-RARBG_31344.png',
 'Cheers.S09E05.1080p.BluRay.x265-RARBG_19512.png',
 'Cheers.S09E05.1080p.BluRay.x265-RARBG_23376.png',
 'Cheers.S09E13.1080p.BluRay.x265-RARBG_16728.png',
 'Cheers.S09E18.1080p.BluRay.x265-RARBG_24528.png',
 'Cheers.S09E19.1080p.BluRay.x265-RARBG_09744.png',
 'Cheers.S09E23.1080p.BluRay.x265-RARBG_06960.png',
 'Cheers.S10E03.1080p.BluRay.x265-RARBG_10176.png',
 'Cheers.S10E05.1080p.BluRay.x265-RARBG_01032.png',
 'Cheers.S10E19.1080p.BluRay.x265-RARBG_06912.png',
 'Cheers.S10E19.1080p.BluRay.x265-RARBG_16776.png',
 'Cheers.S10E22.1080p.BluRay.x265-RARBG_06264.png',
 'Cheers.S10E22.1080p.BluRay.x265-RARBG_18336.png',
 'Cheers.S10E22.1080p.BluRay.x265-RARBG_19992.png',
 'Cheers.S11E08.1080p.BluRay.x265-RARBG_10344.png',
 'Cheers.S11E04.1080p.BluRay.x265-RARBG_27696.png',
 'Cheers.S11E10.1080p.BluRay.x265-RARBG_24840.png',
 'Cheers.S11E13.1080p.BluRay.x265-RARBG_24672.png',
 'Cheers.S11E19.1080p.BluRay.x265-RARBG_00840.png',
 'Cheers.S11E21.1080p.BluRay.x265-RARBG_22272.png',
 'Cheers.S11E23E24.1080p.BluRay.x265-RARBG_45240.png',
 'fargo.s05e02.2160p.web.h265-successfulcrab-sample_0336.png',
 'fargo.s05e06.2160p.web.h265-successfulcrab-sample_0384.png',
 'fargo.s05e06.2160p.web.h265-successfulcrab-sample_0720.png',
 'For.All.Mankind.S01E01.1080p.WEBRip.x265-RARBG_21456.png',
 'For.All.Mankind.S01E03.1080p.WEBRip.x265-RARBG_51744.png',
 'For.All.Mankind.S01E04.1080p.WEBRip.x265-RARBG_28752.png',
 'For.All.Mankind.S02E05.1080p.WEBRip.x265-RARBG_67536.png',
 'For.All.Mankind.S02E09.1080p.WEBRip.x265-RARBG_07632.png',
 'Frasier.S01E01.The.Good.Son.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_22608.png',
 'Frasier.S01E02.Space.Quest.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_15360.png',
 'Frasier.S01E03.Dinner.at.Eight.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_03912.png',
 'Frasier.S01E10.Oops.1080p.BluRay10Bit.Dts-HDMa2.0.HEVC-d3g_03648.png',
 'Frasier.S01E12.Miracle.on.Third.or.Fourth.Street.1080p.BluRay10Bit.Dts-HDMa2.0.HEVC-d3g_07200.png',
 'Frasier.S01E13.Guess.Whos.Coming.to.Breakfast.1080p.BluRay.R10Bit.Dts-HDMa2.0.HEVC-d3g_05832.png',
 'Frasier.S01E15.You.Cant.Tell.a.Crook.by.His.Cover.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_17496.png',
 'Frasier.S02E05.Dukes.We.Hardly.Knew.Ye.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_31704.png',
 'Frasier.S02E07.The.Candidate.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_03648.png',
 'Frasier.S02E09.Adventures.in.Paradise.2.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_12792.png',
 'Frasier.S02E10.Burying.a.Grudge.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_22248.png',
 'Frasier.S03E07.The.Adventures.of.Bad.Boy.and.Dirty.Girl.2.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_28392.png',
 'Frasier.S03E09.Frasier.Grinch.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_22608.png',
 'Frasier.S03E19.Crane.vs.Crane.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_14784.png',
 'Frasier.S03E21.Where.Theres.Smoke.Theres.Fired.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_25488.png',
 'Frasier.S04E02.Love.Bites.Dog.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_06504.png',
 'Frasier.S04E04.A.Cranes.Critique.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_16200.png',
 'Frasier.S04E05.Head.Game.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_02184.png',
 'Frasier.S04E11.Three.Days.of.the.Condo.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_14688.png',
 'Frasier.S04E14.To.Kill.a.Talking.Bird.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_00264.png',
 'Frasier.S04E22.Are.You.Being.Served.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_07320.png',
 'Frasier.S05E11.Aint.Nobodys.Business.If.I.Do.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_28560.png',
 'Frasier.S05E16.Beware.of.Greeks.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_11448.png',
 'Frasier.S05E16.Beware.of.Greeks.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_16464.png',
 'Frasier.S05E17.The.Perfect.Guy.1080p.BluRay10Bit.Dts-HDMa2.0.HEVC-d3g_14448.png',
 'Frasier.S05E21.Roz.and.the.Schnoz.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_20112.png',
 'Frasier.S06E13.The.Show.Where.Woody.Shows.Up.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_29592.png',
 'Frasier.S06E17.Dinner.Party.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_03768.png',
 'Frasier.S07E19.Morning.Becomes.Entertainment.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_24984.png',
 'Frasier.S07E19.Morning.Becomes.Entertainment.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_25104.png',
 'Frasier.S07E23-E24.Something.Borrowed.Someone.Blue.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_01920.png',
 'Frasier.S08E16.Docu.Drama.1080p.BluRay10Bit.Dts-HDMa2.0.HEVC-d3g_07488.png',
 'Frasier.S09E10.Junior.Agent.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_27552.png',
 'Frasier.S09E14.Juvenilia.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_09576.png',
 'Frasier.S09E18.War.of.the.Words.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_27360.png',
 'Frasier.S10E04.Kissing.Cousin.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_21480.png',
 'Frasier.S10E09.Dont.Go.Breaking.My.Heart.3.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_28992.png',
 'Frasier.S10E13.Lilith.Needs.a.Favor.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_21936.png',
 'Frasier.S10E19.Some.Assembly.Required.1080p.BluRay10Bit.Dts-HDMa2.0.HEVC-d3g_06984.png',
 'Frasier.S11E01.No.Sex.Please.Were.Skittish.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_16128.png',
 'Frasier.S11E03.The.Doctor.is.Out.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_16368.png',
 'Frasier.S11E04.The.Babysitter.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_20568.png',
 'Frasier.S11E08.Murder.Most.Maris.2.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_05736.png',
 'Frasier.S11E08.Murder.Most.Maris.2.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_13320.png',
 'Frasier.S11E10.Seabee.Jeebies.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_27816.png',
 'Frasier.S11E11.High.Holidays.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_32160.png',
 'Frasier.S11E12.Frasier.Lite.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_29472.png',
 'Frasier.S11E23-E24.Goodnight.Seattle.1080p.BluRay.10Bit.Dts-HDMa2.0.HEVC-d3g_25968.png',
 'Fringe.S01E14.Ability.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_60384.png',
 'Fringe.S01E19.The.Road.Not.Taken.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_20568.png',
 'Fringe.S02E02.Night.of.Desirable.Objects.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_30216.png',
 'Fringe.S02E03.Fracture.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_13296.png',
 'Fringe.S02E05.Dream.Logic.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_16008.png',
 'Fringe.S02E06.Earthling.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_42336.png',
 'Fringe.S02E11.Unearthed.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_02472.png',
 'Fringe.S02E19.The.Man.from.the.Other.Side.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_42288.png',
 'Fringe.S02E20.Brown.Betty.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_52584.png',
 'Fringe.S02E22.Over.There.(1).1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_02232.png',
 'Fringe.S03E02.The.Box.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_56880.png',
 'Fringe.S03E07.The.Abducted.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_59400.png',
 'Fringe.S04E01.Neither.Here.Nor.There.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_33072.png',
 'Fringe.S04E01.Neither.Here.Nor.There.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_54192.png',
 'Fringe.S04E04.Subject.9.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_29760.png',
 'Fringe.S05E05.An.Origin.Story.1080p.BluRay.10bit.x265.HEVC.DD.5.1-PHOCiS_47136.png',
 'From.S01E06.Book.74.2160p.WEB-DL.DDP5.1.HEVC-TEPES_50496.png',
 'From.S01E08.Broken.Windows.Open.Doors.2160p.WEB-DL.DDP5.1.HEVC-TEPES_47592.png',
 'Legion.S01E05.1080p.BluRay.x265-RARBG_34512.png',
 'Legion.S01E03.1080p.BluRay.x265-RARBG_12336.png',
 'Legion.S02E04.1080p.WEBRip.x265-RARBG_11544.png',
 'Legion.S02E11.1080p.WEBRip.x265-RARBG_52752.png',
 'Legion.S03E02.1080p.WEBRip.x265-RARBG_27384.png',
 'Legion.S03E06.1080p.WEBRip.x265-RARBG_50808.png',
 'Lost.Girl.S02E05.BrotherFae.of.the.Wolves.BluRay.10Bit.1080p.DD5.1.H265-d3g_27072.png',
 'Lost.Girl.S02E12.Masks.BluRay.10Bit.1080p.DD5.1.H265-d3g_39624.png',
 'Lost.Girl.S02E15.Table.For.Fae.BluRay.10Bit.1080p.DD5.1.H265-d3g_20832.png',
 'Lost.Girl.S02E16.Schools.Out.BluRay.10Bit.1080p.DD5.1.H265-d3g_35400.png',
 'Lost.Girl.S02E18.Fae-nted.Love.BluRay.10Bit.1080p.DD5.1.H265-d3g_18960.png',
 'Lost.Girl.S02E21.Into.the.Dark.BluRay.10Bit.1080p.DD5.1.H265-d3g_44376.png',
 'Lost.Girl.S03E09.Ceremony.BluRay.10Bit.1080p.DD5.1.H265-d3g_26280.png',
 'Lost.Girl.S03E11.Adventures.in.Fae-bysitting.BluRay.10Bit.1080p.DD5.1.H265-d3g_16776.png',
 'Lost.Girl.S03E11.Adventures.in.Fae-bysitting.BluRay.10Bit.1080p.DD5.1.H265-d3g_56232.png',
 'Lost.Girl.S03E13.Those.Who.Wander.BluRay.10Bit.1080p.DD5.1.H265-d3g_54360.png',
 'Lost.Girl.S04E01.In.Memoriam.BluRay.10Bit.1080p.DD5.1.H265-d3g_40080.png',
 'Lost.Girl.S04E04.Turn.to.Stone.BluRay.10Bit.1080p.DD5.1.H265-d3g_05568.png',
 'Lost.Girl.S05E04.When.God.Opens.a.Window.BluRay.10Bit.1080p.DD5.1.H265-d3g_02424.png',
 'Lost.Girl.S05E06.Clear.Eyes.Fae.Hearts.BluRay.10Bit.1080p.DD5.1.H265-d3g_29424.png',
 'Lost.Girl.S05E12.Judgement.Fae.BluRay.10Bit.1080p.DD5.1.H265-d3g_55512.png',
 'Lost.Girl.S05E14.Follow.the.Yellow.Trick.Road.BluRay.10Bit.1080p.DD5.1.H265-d3g_62184.png',
 'Modern.Family.S01E07.1080p.BluRay.x265-RARBG_16752.png',
 'Modern.Family.S01E09.1080p.BluRay.x265-RARBG_06576.png',
 'Modern.Family.S01E15.1080p.BluRay.x265-RARBG_07752.png',
 'Modern.Family.S01E23.1080p.BluRay.x265-RARBG_10200.png',
 'Modern.Family.S02E01.1080p.BluRay.x265-RARBG_29952.png',
 'Modern.Family.S02E10.1080p.BluRay.x265-RARBG_19200.png',
 'Modern.Family.S02E13.1080p.BluRay.x265-RARBG_28992.png',
 'Modern.Family.S02E16.1080p.BluRay.x265-RARBG_25152.png',
 'Modern.Family.S03E01.1080p.BluRay.x265-RARBG_09000.png',
 'Modern.Family.S03E08.1080p.BluRay.x265-RARBG_23784.png',
 'Modern.Family.S03E20.1080p.BluRay.x265-RARBG_14808.png',
 'Modern.Family.S03E24.1080p.BluRay.x265-RARBG_28344.png',
 'Modern.Family.S04E03.1080p.BluRay.x265-RARBG_20808.png',
 'Modern.Family.S04E06.1080p.BluRay.x265-RARBG_26304.png',
 'Modern.Family.S04E09.1080p.BluRay.x265-RARBG_19200.png',
 'Modern.Family.S05E04.Farm.Strong.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_06816.png',
 'Modern.Family.S05E05.The.Late.Show.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_28104.png',
 'Modern.Family.S05E09.The.Big.Game.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_07056.png',
 'Modern.Family.S05E22.Message.Received.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_17832.png',
 'Modern.Family.S05E24.The.Wedding.Part.2.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_28800.png',
 'Modern.Family.S06E18.Spring.Break.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_15120.png',
 'Modern.Family.S06E19.Grill.Interrupted.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_12000.png',
 'Modern.Family.S07E07.Phils.Sexy.Sexy.House.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_07344.png',
 'Modern.Family.S07E15.I.Dont.Know.How.She.Does.It.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_06144.png',
 'Modern.Family.S09E04.Sex.Lies.and.Kickball.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_27864.png',
 'Modern.Family.S09E13.In.Your.Head.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_17856.png',
 'Modern.Family.S09E15.Spanks.for.the.Memories.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_14112.png',
 'Modern.Family.S09E15.Spanks.for.the.Memories.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_24240.png',
 'Modern.Family.S09E22.Clash.of.Swords.1080p.DSNP.WEB-DL.DDP5.1.H.264-CRFW_16632.png',
 'Modern.Family.S10E03.A.Sketchy.Area.1080p.DSNP.WEB-DL.DDP5.1.H.264-OLDFAMiLY_14688.png',
 'Modern.Family.S10E08.Kids.These.Days.1080p.DSNP.WEB-DL.DDP5.1.H.264-OLDFAMiLY_21456.png',
 'Modern.Family.S10E11.A.Moving.Day.1080p.DSNP.WEB-DL.DDP5.1.H.264-OLDFAMiLY_27360.png',
 'Modern.Family.S11E09.The.Last.Christmas.1080p.DSNP.WEB-DL.DDP5.1.H.264-WKS_26784.png',
 'Modern.Family.S11E12.Dead.on.a.Rival.1080p.DSNP.WEB-DL.DDP5.1.H.264-ZigZag_18888.png',
 'Modern.Family.S11E12.Dead.on.a.Rival.1080p.DSNP.WEB-DL.DDP5.1.H.264-ZigZag_25152.png',
 'Modern.Family.S11E14.Spuds.1080p.DSNP.WEB-DL.DDP5.1.H.264-ZigZag_17520.png',
 'Party Down (2009) - S01E02 - California College Conservative Union Caucus (1080p AMZN WEBRip x265 Panda)_15720.png',
 'Party Down (2009) - S01E08 - Celebrate Ricky Sargulesh (1080p AMZN WEBRip x265 Panda)_21144.png',
 'Russian.Doll.S01E02.2160p.HDR.NF.WEBRip.DDP5.1.x265-TrollUHD_21696.png',
 'Russian.Doll.S01E03.2160p.HDR.NF.WEBRip.DDP5.1.x265-TrollUHD_08352.png',
 'Scrubs S01E08 My Fifteen Minutes (c)  [1080p x265 10bit Joy]_39048.png',
 'Scrubs S01E11 My Own Personal Jesus  [1080p x265 10bit Joy]_30432.png',
 'Scrubs S01E13 My Balancing Act  [1080p x265 10bit Joy]_14520.png',
 'Scrubs S01E21 My Sacrificial Clam (c)  [1080p x265 10bit Joy]_10968.png',
 'Scrubs S02E12 My New Old Friend  [1080p x265 10bit Joy]_29664.png',
 'Scrubs S03E08 My Friend the Doctor  [1080p x265 10bit Joy]_07656.png',
 'Scrubs S03E13 My Porcelain God  [1080p x265 10bit Joy]_22128.png',
 'Scrubs S03E16 My Butterfly  [1080p x265 10bit Joy]_34848.png',
 "Scrubs S04E01 My Old Friend's New Friend  [1080p x265 10bit Joy]_04680.png",
 'Scrubs S04E03 My New Game  [1080p x265 10bit Joy]_14808.png',
 'Scrubs S04E10 My Female Trouble  [1080p x265 10bit Joy]_11712.png',
 'Scrubs S04E11 My Unicorn  [1080p x265 10bit Joy]_24984.png',
 'Scrubs S04E23 My Faith In Humanity  [1080p x265 10bit Joy]_03456.png',
 'Scrubs S04E23 My Faith In Humanity  [1080p x265 10bit Joy]_28080.png',
 'Scrubs S05E04 My Jiggly Ball  [1080p x265 10bit Joy]_11880.png',
 'Scrubs S05E08 My Big Bird (c)  [1080p x265 10bit Joy]_20016.png',
 'Scrubs S05E19 His Story III  [1080p x265 10bit Joy]_24768.png',
 'Scrubs S05E19 His Story III  [1080p x265 10bit Joy]_31824.png',
 'Scrubs S05E23 My Urologist  [1080p x265 10bit Joy]_01584.png',
 'Scrubs S05E23 My Urologist  [1080p x265 10bit Joy]_21864.png',
 'Scrubs S05E23 My Urologist  [1080p x265 10bit Joy]_32952.png',
 "Scrubs S06E02 My Best Friend's Baby's Baby and My Baby's Baby  [1080p x265 10bit Joy]_04272.png",
 'Scrubs S06E03 My Coffee  [1080p x265 10bit Joy]_22536.png',
 'Scrubs S06E04 My House  [1080p x265 10bit Joy]_28272.png',
 'Scrubs S07E01 My Own Worst Enemy  [1080p x265 10bit Joy]_07056.png',
 'Scrubs S07E03 My Inconvenient Truth  [1080p x265 10bit Joy]_03096.png',
 'Scrubs S07E05 My Growing Pains  [1080p x265 10bit Joy]_25608.png',
 'Scrubs S07E11 My Princess  [1080p x265 10bit Joy]_07944.png',
 'Scrubs S08E06 My Cookie Pants  [1080p x265 10bit Joy]_12792.png',
 'Scrubs S08E11 My Nah Nah Nah  [1080p x265 10bit Joy]_12792.png',
 'Scrubs S08E17 My Chief Concern  [1080p x265 10bit Joy]_10488.png',
 'Scrubs S08E19 My Finale Part 2  [1080p x265 10bit Joy]_27144.png',
 'Scrubs S08E19 My Finale Part 2  [1080p x265 10bit Joy]_30480.png',
 'Scrubs S09E05 Our Mysteries  [1080p x265 10bit Joy]_03432.png',
 'Seinfeld.S03E17.1080p.WEBRip.x265-RARBG_56736.png',
 'Seinfeld.S04E02.1080p.WEBRip.x265-RARBG_26184.png',
 'Seinfeld.S04E07.1080p.WEBRip.x265-RARBG_12552.png',
 'Seinfeld.S04E08.1080p.WEBRip.x265-RARBG_09048.png',
 'Seinfeld.S04E17.1080p.WEBRip.x265-RARBG_27144.png',
 'Seinfeld.S05E07.1080p.WEBRip.x265-RARBG_14112.png',
 'Seinfeld.S05E13.1080p.WEBRip.x265-RARBG_25896.png',
 'Seinfeld.S05E17.1080p.WEBRip.x265-RARBG_12648.png',
 'Seinfeld.S06E22.1080p.WEBRip.x265-RARBG_11832.png',
 'Seinfeld.S07E06.1080p.WEBRip.x265-RARBG_23184.png',
 'Seinfeld.S08E06.1080p.WEBRip.x265-RARBG_15096.png',
 'Seinfeld.S08E06.1080p.WEBRip.x265-RARBG_17328.png',
 'Seinfeld.S08E12.1080p.WEBRip.x265-RARBG_13344.png',
 'Seinfeld.S08E12.1080p.WEBRip.x265-RARBG_14256.png',
 'Seinfeld.S08E15.1080p.WEBRip.x265-RARBG_31272.png',
 'Seinfeld.S08E16.1080p.WEBRip.x265-RARBG_18840.png',
 'Seinfeld.S09E01.1080p.WEBRip.x265-RARBG_14688.png',
 'Seinfeld.S09E02.1080p.WEBRip.x265-RARBG_31872.png',
 'Seinfeld.S09E12.1080p.WEBRip.x265-RARBG_29304.png',
 'Seinfeld.S09E19.1080p.WEBRip.x265-RARBG_14304.png',
 'Seinfeld.S09E22.1080p.WEBRip.x265-RARBG_02568.png',
 'Servant.S03E07.Camp.2160p.ATVP.WEB-DL.DDP5.1.HDR.HEVC-CasStudio_35232.png',
 'Servant.S03E09.Commitment.2160p.ATVP.WEB-DL.DDP5.1.HDR.HEVC-CasStudio_36528.png',
 'Silo.S01E10.Outside.2160p.ATVP.WEB-DL.DDP5.1.HDR.H.265-NTb_04968.png',
 'Suits.S04E02.1080p.BluRay.x265-RARBG_35496.png',
 'Suits.S04E12.1080p.BluRay.x265-RARBG_53376.png',
 'Suits.S05E11.1080p.BluRay.x265-RARBG_15576.png',
 'Suits.S06E15.1080p.BluRay.x265-RARBG_42504.png',
 'Ted.Lasso.S02E04.Carol.of.the.Bells.AAC.5.1.1080p.WEBRip.x265-SiQ_05352.png',
 'Ted.Lasso.S02E07.Headspace.AAC.5.1.1080p.WEBRip.x265-SiQ_04896.png',
 'Ted.Lasso.S02E07.Headspace.AAC.5.1.1080p.WEBRip.x265-SiQ_42432.png',
 'Ted.Lasso.S02E09.Beard.After.Hours.AAC.5.1.1080p.WEBRip.x265-SiQ_48240.png',
 'The.Leftovers.S01E04.BluRay.1080p.Dts.H265-d3g_31920.png',
 'The.Leftovers.S01E07.BluRay.1080p.Dts.H265-d3g_50112.png',
 'The.Leftovers.S02E02.BluRay.1080p.Dts.H265-d3g_25080.png',
 'The.Leftovers.S03E01.BluRay.1080p.Dts.H265-d3g_22632.png',
 'The.Prisoner.1967.S01E11.Its.Your.Funeral.1080p.BluRay.x264-CiNEFiLE_49512.png',
 'The.Resort.S01E02.A.Noxious.Toothworm.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_03696.png',
 'The.Resort.S01E03.Tempus.Exhaurire.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_41232.png',
 'The.Resort.S01E04.The.History.of.Forgetting.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_29448.png',
 'The.Resort.S01E08.The.Disillusionment.of.Time.2160p.STAN.WEB-DL.DDP5.1.H.265-dB_27672.png',
 'The.X-Files.S01E01.Pilot.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_38592.png',
 'The.X-Files.S01E05.The.Jersey.Devil.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_57816.png',
 'The.X-Files.S01E08.Ice.1080p.BluRay.10Bit.Dts-HDMa5.1.HEVC-d3g_20400.png',

In [94]:
a = retina_df[retina_df['pct_of_frame'] > 0.005]
eph = a.merge(faces,
                                                         on=['name', 'face_num'],
                                                         how='left')

(1361, 23)

In [95]:
fp = eph[eph['x1_y'].isna()]
fp.shape

(34, 23)

In [96]:
34/1361

0.024981631153563555

In [97]:
152/1979

0.07680646791308741

In [100]:
eph['status'] = eph.apply(lambda x: 'tp' if not pd.isnull(x['x1_y']) else 'fp', axis=1)

In [101]:
g = eph.groupby('status').count()
g

,name,face_num,x1_x,y1_x,x2_x,y2_x,width_x,height_x,area_x,confidence,...,img_height_y,img_width_y,x1_y,y1_y,x2_y,y2_y,width_y,height_y,area_y,pct_of_frame_y
status,,,,,,,,,,,,,,,,,,,,,
fp,34,34,34,34,34,34,34,34,34,34,...,0,0,0,0,0,0,0,0,0,0
tp,1327,1327,1327,1327,1327,1327,1327,1327,1327,1327,...,1327,1327,1327,1327,1327,1327,1327,1327,1327,1327

In [102]:
temp = faces.merge(retina_df, 
                   on=['name', 'face_num'],
                   how='left')
temp

,name,img_height_x,img_width_x,x1_x,y1_x,x2_x,y2_x,width_x,height_x,area_x,...,y1_y,x2_y,y2_y,width_y,height_y,area_y,confidence,img_width_y,img_height_y,pct_of_frame_y
0,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png,1080,1920,323,5,919,731,596,726,432696,...,190.0,926.0,712.0,392.0,522.0,204624.0,0.999803,1920.0,1080.0,0.098681
1,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png,1080,1920,262,42,614,507,352,465,163680,...,104.0,528.0,491.0,252.0,387.0,97524.0,0.999671,1920.0,1080.0,0.047031
2,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,484,389,671,617,187,228,42636,...,81.0,1107.0,262.0,105.0,181.0,19005.0,0.999594,1920.0,1080.0,0.009165
3,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,1003,42,1195,261,192,219,42048,...,411.0,668.0,598.0,125.0,187.0,23375.0,0.999471,1920.0,1080.0,0.011273
4,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png,1080,1920,1121,66,1662,824,541,758,410078,...,186.0,1548.0,807.0,427.0,621.0,265167.0,0.999094,1920.0,1080.0,0.127878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,Will.&.Grace.S11E08.Lies.&.Whispers.1080p.Web....,1080,1920,1612,261,1704,361,92,100,9200,...,274.0,1673.0,351.0,56.0,77.0,4312.0,0.997497,1920.0,1080.0,0.002079
1891,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...,1080,1920,457,103,579,237,122,134,16348,...,231.0,860.0,324.0,73.0,93.0,6789.0,0.999080,1920.0,1080.0,0.003274
1892,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...,1080,1920,778,223,868,330,90,107,9630,...,114.0,575.0,232.0,85.0,118.0,10030.0,0.998779,1920.0,1080.0,0.004837
1893,Will.&.Grace.S11E14.The.Favourite.1080p.Web.h2...,1080,1920,1240,204,1313,331,73,127,9271,...,215.0,1300.0,323.0,58.0,108.0,6264.0,0.994483,1920.0,1080.0,0.003021
1894,Will.&.Grace.S11E17.New.Crib.1080p.Web.h264-JB...,1080,1920,990,139,1254,424,264,285,75240,...,149.0,1192.0,407.0,195.0,258.0,50310.0,0.999755,1920.0,1080.0,0.024262

In [104]:
fn = temp[temp['x1_y'].isna()]
fn

,name,img_height_x,img_width_x,x1_x,y1_x,x2_x,y2_x,width_x,height_x,area_x,...,y1_y,x2_y,y2_y,width_y,height_y,area_y,confidence,img_width_y,img_height_y,pct_of_frame_y
33,Billions.S06E10.1080p.WEBRip.x265-RARBG_73680.png,1080,1920,1531,217,1722,438,191,221,42211,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Billions.S06E10.1080p.WEBRip.x265-RARBG_73680.png,1080,1920,1484,280,1574,440,90,160,14400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Carnivale.S02E03.1080p.WEBRip.10Bit.EAC3.H265-...,1080,1920,742,42,1513,827,771,785,605235,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Cheers.S01E20.1080p.BluRay.x265-RARBG_24480.png,1080,1448,0,451,135,679,135,228,30780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,Cheers.S04E14.1080p.BluRay.x265-RARBG_07608.png,1080,1440,1294,430,1440,631,146,201,29346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600,White.Collar.S01E05.1080p.BluRay.x265-RARBG_09...,1080,1920,1716,381,1750,444,34,63,2142,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1606,White.Collar.S01E12.1080p.BluRay.x265-RARBG_53...,1080,1920,1356,251,1437,392,81,141,11421,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1637,White.Collar.S03E07.1080p.WEBRip.x265-RARBG_09...,1080,1920,1057,363,1163,483,106,120,12720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1675,Will.&.Grace.S02E19.An.Affair.to.Forget.480p.W...,480,640,601,82,640,226,39,144,5616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1803,Will.&.Grace.S07E21.Its.a.Dad.Dad.Dad.Dad.Worl...,1080,1920,351,924,577,1080,226,156,35256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
68/1895

0.035883905013192614

In [2]:
import pandas as pd 

df = pd.read_csv('../data/video_dimensions.csv', index_col=0)
df.head()

,fp,width,height,resolution,aspect_ratio,aspect_ratio_coded
0,/home/amos/media/tv/Manhunt.2024.S01E03.Let.th...,3840,1608,4k,2.388060,2.35
1,/home/amos/media/tv/Alone.S10E09.Splintered.10...,1920,1080,1080p,1.777778,1.85
2,/home/amos/media/tv/Alone.S10E02.1080p.WEB.h26...,1920,1080,1080p,1.777778,1.85
3,/home/amos/media/tv/Alone.S10E02.1080p.WEB.h26...,1920,1080,1080p,1.777778,1.85
4,/home/amos/media/tv/Constellation.S01E04.HDR.2...,3840,2160,4k,1.777778,1.85

In [5]:
g = df.groupby('resolution').max()
g['fp'].values

array(['/home/amos/media/tv/modern_family/Modern.Family.S11.1080p.DSNP.WEB-DL.DDP5.1.H.264-MIXED/Modern.Family.S11E18.Finale.Part.2.1080p.DSNP.WEB-DL.DDP5.1.H.264-ZigZag.mkv',
       '/home/amos/media/tv/Will.&.Grace.S01-S11.480p.1080p.WEB-DL.AAC.DDP5.1.h264-JBee/Season 07/Will.&.Grace.S07E09.Saving.Grace.Again.Part.2.480p.Web.h264-JBee.mkv',
       '/home/amos/media/tv/the_curse_2023/The.Curse.2023.S01E03.HDR.2160p.WEB.H265-ActivePlatinumCaracalOfAwe/the.curse.2023.s01e03.hdr.2160p.web.h265-activeplatinumcaracalofawe.mkv',
       '/home/amos/media/tv/The Simpsons.S01-S31.1080p.WEB-DL.BluRay.10bit.x265.HEVC-PHOCiS/Season 03/The.Simpsons.S03E01.Stark.Raving.Dad.720p.HDTV.10bit.x265.HEVC-PHOCiS.mkv'],
      dtype=object)