In [2]:
import pandas as pd

In [11]:
df = pd.read_csv('../../data/test_predicted.csv', index_col=0)
df.head()

,x1,y1,x2,y2,right_eye_x,right_eye_y,left_eye_x,left_eye_y,nose_x,nose_y,...,face_num,frame_num,img_width,img_height,filepath,encoding,label,encoding_facenet,predicted_name,predicted_tmdb_id
0,0.216,0.234,0.361,0.599,0.295,0.396,0.337,0.368,0.352,0.438,...,0,192,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.04528122e-01,4.26750705e-02,9.92560610e-02...",NaN,"[0.16128922998905182, 1.389657735824585, -1.45...",Robin Tunney,17346.0
1,0.001,0.186,0.078,0.392,0.037,0.272,0.068,0.267,0.064,0.304,...,1,192,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.09764203e-01,1.01907797e-01,4.41615433e-02...",NaN,"[-0.4058889150619507, -1.0181241035461426, -1....",NaN,NaN
2,0.404,0.205,0.537,0.562,0.475,0.355,0.506,0.330,0.523,0.400,...,0,216,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.10503129,0.02722587,0.11773209,-0.02752084...",NaN,"[-0.9048962593078613, 1.4389667510986328, -0.3...",Robin Tunney,17346.0
3,0.188,0.165,0.275,0.377,0.235,0.249,0.265,0.250,0.263,0.281,...,1,216,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.17259115,0.08089909,0.09485973,-0.01292775...",NaN,"[1.5663477182388306, -0.6882420182228088, -1.6...",NaN,NaN
4,0.042,0.121,0.108,0.288,0.075,0.187,0.099,0.188,0.098,0.210,...,2,216,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.19313513,0.11090928,0.06218918,-0.07306869...",NaN,"[-0.10494174808263779, 0.23639324307441711, -1...",NaN,NaN

In [12]:
df[df['predicted_name'].notna()]

,x1,y1,x2,y2,right_eye_x,right_eye_y,left_eye_x,left_eye_y,nose_x,nose_y,...,face_num,frame_num,img_width,img_height,filepath,encoding,label,encoding_facenet,predicted_name,predicted_tmdb_id
0,0.216,0.234,0.361,0.599,0.295,0.396,0.337,0.368,0.352,0.438,...,0,192,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.04528122e-01,4.26750705e-02,9.92560610e-02...",NaN,"[0.16128922998905182, 1.389657735824585, -1.45...",Robin Tunney,17346.0
2,0.404,0.205,0.537,0.562,0.475,0.355,0.506,0.330,0.523,0.400,...,0,216,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.10503129,0.02722587,0.11773209,-0.02752084...",NaN,"[-0.9048962593078613, 1.4389667510986328, -0.3...",Robin Tunney,17346.0
7,0.361,0.171,0.501,0.529,0.408,0.321,0.471,0.307,0.452,0.366,...,1,240,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.08742733,0.04232186,0.16838558,-0.07984559...",NaN,"[-1.1993138790130615, 0.9519057869911194, -0.5...",Robin Tunney,17346.0
10,0.376,0.242,0.508,0.585,0.418,0.390,0.476,0.374,0.459,0.440,...,0,264,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.0663911,0.01003704,0.14859802,-0.09528915,...",NaN,"[-1.6228691339492798, 1.1488171815872192, -0.2...",Robin Tunney,17346.0
14,0.176,0.232,0.345,0.664,0.230,0.416,0.305,0.396,0.284,0.461,...,0,288,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.22502878e-01,2.56269928e-02,1.00656919e-01...",NaN,"[-1.7275537252426147, 0.657789409160614, -0.65...",Robin Tunney,17346.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,0.503,0.231,0.688,0.644,0.589,0.396,0.663,0.391,0.649,0.475,...,0,62136,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.0589462,0.19723462,0.05126834,-0.04295913,...",NaN,"[0.04349425435066223, 0.040575455874204636, 0....",Robert Sean Leonard,2692.0
3172,0.215,0.000,0.577,0.791,0.273,0.345,0.417,0.236,0.353,0.458,...,0,62160,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.13617839,0.02288584,0.11511527,0.0204379,-...",NaN,"[1.4486738443374634, -1.4824944734573364, 0.89...",Hugh Laurie,41419.0
3173,0.248,0.000,0.622,0.791,0.321,0.346,0.468,0.236,0.411,0.480,...,0,62184,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.11193597,0.01513907,0.05801515,-0.03820986...",NaN,"[1.0963785648345947, -1.4671112298965454, 0.35...",Hugh Laurie,41419.0
3174,0.250,0.000,0.611,0.776,0.322,0.313,0.468,0.220,0.409,0.452,...,0,62208,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-9.80078876e-02,6.62549660e-02,6.70300871e-02...",NaN,"[0.8768793940544128, -1.7966728210449219, 0.05...",Hugh Laurie,41419.0
3175,0.245,0.000,0.608,0.767,0.316,0.330,0.461,0.232,0.401,0.464,...,0,62232,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.10855579,0.05165328,0.05387565,-0.0461226,...",Hugh Laurie,"[1.007337212562561, -1.2549504041671753, 0.406...",Hugh Laurie,41419.0