In [10]:
from pathlib import Path

import cv2
import pandas as pd
from tqdm import tqdm

In [7]:
def pct_of_frame(row):
    x = int((row['x2'] - row['x1']) * row['img_width'])
    y = int((row['y2'] - row['y1']) * row['img_height'])
    xx = row['img_width']
    yy = row['img_height']

    pct_of_frame = (x * y)/(xx * yy)
    return round(pct_of_frame * 100, 2)

In [8]:
df = pd.read_csv('/home/amos/programs/CineFace/data/test_labeled.csv', index_col=0)
df['pct_of_frame'] = df.apply(pct_of_frame, axis=1)
df.head()

,x1,y1,x2,y2,right_eye_x,right_eye_y,left_eye_x,left_eye_y,nose_x,nose_y,...,confidence,face_num,frame_num,img_width,img_height,filepath,encoding,label,encoding_facenet,pct_of_frame
0,0.216,0.234,0.361,0.599,0.295,0.396,0.337,0.368,0.352,0.438,...,0.999,0,192,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.04528122e-01,4.26750705e-02,9.92560610e-02...",NaN,"[0.16128922998905182, 1.389657735824585, -1.45...",5.28
1,0.001,0.186,0.078,0.392,0.037,0.272,0.068,0.267,0.064,0.304,...,0.997,1,192,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.09764203e-01,1.01907797e-01,4.41615433e-02...",NaN,"[-0.4058889150619507, -1.0181241035461426, -1....",1.57
2,0.404,0.205,0.537,0.562,0.475,0.355,0.506,0.330,0.523,0.400,...,0.999,0,216,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.10503129,0.02722587,0.11773209,-0.02752084...",NaN,"[-0.9048962593078613, 1.4389667510986328, -0.3...",4.73
3,0.188,0.165,0.275,0.377,0.235,0.249,0.265,0.250,0.263,0.281,...,0.999,1,216,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.17259115,0.08089909,0.09485973,-0.01292775...",NaN,"[1.5663477182388306, -0.6882420182228088, -1.6...",1.84
4,0.042,0.121,0.108,0.288,0.075,0.187,0.099,0.188,0.098,0.210,...,0.998,2,216,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.19313513,0.11090928,0.06218918,-0.07306869...",NaN,"[-0.10494174808263779, 0.23639324307441711, -1...",1.09

In [9]:
df = df.sort_values(by='pct_of_frame', ascending=True)
df.head()

,x1,y1,x2,y2,right_eye_x,right_eye_y,left_eye_x,left_eye_y,nose_x,nose_y,...,confidence,face_num,frame_num,img_width,img_height,filepath,encoding,label,encoding_facenet,pct_of_frame
1171,0.183,0.231,0.193,0.253,0.186,0.240,0.191,0.239,0.189,0.244,...,0.933,1,21816,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-4.90247086e-02,9.49056894e-02,2.49332599e-02...",NaN,"[0.25747475028038025, 0.11125317215919495, -0....",0.02
23,0.692,0.246,0.700,0.267,0.694,0.255,0.698,0.255,0.696,0.259,...,0.938,0,600,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-7.10393414e-02,7.61251599e-02,5.50069772e-02...",NaN,"[0.5597954392433167, -1.0422539710998535, -0.5...",0.02
1162,0.220,0.244,0.229,0.265,0.222,0.254,0.227,0.253,0.225,0.257,...,0.950,1,21624,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-7.18654990e-02,8.27616602e-02,1.45773264e-02...",NaN,"[-0.16954493522644043, 0.047609563916921616, 0...",0.02
2066,0.969,0.808,0.979,0.836,0.971,0.820,0.972,0.820,0.970,0.825,...,0.927,2,38832,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.01385005,0.12383794,0.06082848,-0.02499347...",NaN,"[0.24177879095077515, 0.3041467070579529, -0.4...",0.03
3120,0.382,0.399,0.394,0.426,0.389,0.410,0.392,0.410,0.392,0.416,...,0.925,0,61008,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-4.28588092e-02,1.12105228e-01,9.44388565e-03...",NaN,"[0.22913360595703125, -0.15824675559997559, -0...",0.03

In [17]:
dst = Path('/home/amos/programs/CineFace/data/images/House.S01E01')
cap = cv2.VideoCapture(df.at[0, 'filepath'])
for num, (idx, row) in enumerate(tqdm(df.iterrows(), total=df.shape[0])):
    cap.set(cv2.CAP_PROP_POS_FRAMES, row['frame_num'])
    ret, frame = cap.read()
    x1 = int(row['x1'] * row['img_width'])
    y1 = int(row['y1'] * row['img_height'])
    x2 = int(row['x2'] * row['img_width'])
    y2 = int(row['y2'] * row['img_height'])
    face = frame[y1:y2, x1:x2]
    name = f'{num}_{idx}_{frame_num}_{row["face_num"]}.png'
    fp = dst.joinpath(name)
    cv2.imwrite(str(fp), face)

 29%|██▉       | 915/3176 [03:25<08:27,  4.46it/s]

KeyboardInterrupt: