In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../data/label_df_results.csv', index_col=0)
df.head()

,x1,y1,x2,y2,encoding,tmdb_id,filepath,series_id,season,episode,pct_of_frame,result,threshold
0,714,144,900,402,"[0.20887960493564606, -0.05747608467936516, -1...",NaN,/home/amos/media/tv/Raising Hope (2010) Season...,1615919,3,14,0.023142,1,0.00
1,714,144,900,402,"[0.20887960493564606, -0.05747608467936516, -1...",NaN,/home/amos/media/tv/Raising Hope (2010) Season...,1615919,3,14,0.023142,1,0.05
2,714,144,900,402,"[0.20887960493564606, -0.05747608467936516, -1...",NaN,/home/amos/media/tv/Raising Hope (2010) Season...,1615919,3,14,0.023142,1,0.10
3,714,144,900,402,"[0.20887960493564606, -0.05747608467936516, -1...",NaN,/home/amos/media/tv/Raising Hope (2010) Season...,1615919,3,14,0.023142,1,0.15
4,714,144,900,402,"[0.20887960493564606, -0.05747608467936516, -1...",NaN,/home/amos/media/tv/Raising Hope (2010) Season...,1615919,3,14,0.023142,1,0.20

In [3]:
g = df[['threshold', 'result']].groupby('threshold').mean()
g

             result
threshold
0.00       0.581818
0.05       0.581818
0.10       0.581818
0.15       0.581818
0.20       0.581818
0.25       0.581818
0.30       0.579221
0.35       0.579221
0.40       0.579221
0.45       0.574026
0.50       0.566234
0.55       0.532468
0.60       0.462338
0.65       0.363636
0.70       0.270130
0.75       0.155844
0.80       0.083117
0.85       0.044156
0.90       0.036364
0.95       0.036364