In [8]:
from pathlib import Path 

import pandas as pd

In [4]:
faces = pd.read_csv('../data/faces.csv', index_col=0)
faces.head()

,name,img_height,img_width,x1,y1,x2,y2,width,height,area,pct_of_frame,face_num
0,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png,1080,1920,323,5,919,731,596,726,432696,0.208669,0
1,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png,1080,1920,262,42,614,507,352,465,163680,0.078935,0
2,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,484,389,671,617,187,228,42636,0.020561,0
3,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080,1920,1003,42,1195,261,192,219,42048,0.020278,1
4,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png,1080,1920,1121,66,1662,824,541,758,410078,0.197761,0

In [10]:
images = pd.DataFrame([{'name': x.name} for x in Path('../test_images').iterdir()])
images.head()

                                                name
0  Frasier.S08E01-E02.And.the.Dish.Ran.Away.with....
1  Silo.S01E09.The.Getaway.2160p.ATVP.WEB-DL.DDP5...
2  Will.&.Grace.S03E24.Sons.and.Lovers.Part.I.480...
3     Suits.S03E05.1080p.BluRay.x265-RARBG_40416.png
4  Will.&.Grace.S05E24.Season.Finale.480p.Web.h26...

In [16]:
temp = images[~images['name'].isin(faces['name'])]
temp

                                                   name
5     Frasier.S03E07.The.Adventures.of.Bad.Boy.and.D...
6     Fringe.S03E02.The.Box.1080p.BluRay.10bit.x265....
16    Seinfeld.S03E18.1080p.WEBRip.x265-RARBG_06960.png
17    Scrubs S05E03 My Day at the Races  [1080p x265...
22      Cheers.S10E23.1080p.BluRay.x265-RARBG_23184.png
...                                                 ...
1008  For.All.Mankind.S02E01.1080p.WEBRip.x265-RARBG...
1030    Cheers.S04E22.1080p.BluRay.x265-RARBG_02184.png
1037  Modern.Family.S05E21.Sleeper.1080p.DSNP.WEB-DL...
1049  White.Collar.S02E11.1080p.WEBRip.x265-RARBG_23...
1061  The.X-Files.S01E10.Fallen.Angel.1080p.BluRay.1...

[102 rows x 1 columns]